"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {createHandler}=require("../api/orders"),{MemoryOrderRepository}=require("../server/order-repository"),{assertLocation}=require("../server/order-service");
const root=path.resolve(__dirname,"..");
function payload(code="RP0001"){return{serviceCode:code,description:"Instalação solicitada",address:{street:"Rua A",number:"10",neighborhood:"Centro",city:"Belo Horizonte",postalCode:"30110-000",state:"MG"},urgency:"Hoje",customer:{name:"Cliente",whatsapp:"31999999999"},termsAcceptance:{accepted:true,displayedDocumentVersion:"customer-service-terms-v1"}}}
async function request(handler,body,key="attempt-1"){const res={headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(v){this.body=v}};await handler({method:"POST",headers:{"content-type":"application/json","idempotency-key":key},body},res);return res;}
test("API de pedidos sempre responde JSON padronizado e repete protocolo por idempotência",async()=>{const handler=createHandler({repository:new MemoryOrderRepository()});for(const code of ["RP0001","RP0023","RP0012"]){const first=await request(handler,payload(code),`same-${code}`),retry=await request(handler,payload(code),`same-${code}`);assert.equal(first.statusCode,201);assert.equal(first.headers["content-type"],"application/json; charset=utf-8");assert.equal(first.body.ok,true);assert.match(first.body.protocol,/./);assert.equal(retry.body.orderId,first.body.orderId);assert.equal(retry.body.protocol,first.body.protocol)}const error=await request(handler,{...payload(),termsAcceptance:{accepted:false}},"error");assert.equal(error.body.ok,false);assert.equal(typeof error.body.code,"string");assert.equal(typeof error.body.error,"string");assert.match(error.headers["content-type"],/application\/json/);});
test("termos públicos não expõem códigos internos e preservam garantias",()=>{const files=["docs/customer-service-terms-v1.md","docs/provider-service-agreement-v1.md"],forbidden=/CHANGE_ORDER|CUSTOMER_REQUEST|PROVIDER_ANALYSIS|PROVIDER_QUOTE_SUBMITTED|PLATFORM_REVIEW|QUOTE_APPROVED|CUSTOMER_QUOTE_SENT|CUSTOMER_APPROVED|PROVIDER_AUTHORIZED|SERVICE_STARTED|customerId|termsHash|acceptanceEvidenceId/;for(const file of files)assert.doesNotMatch(fs.readFileSync(path.join(root,file),"utf8"),forbidden);const customer=fs.readFileSync(path.join(root,files[0]),"utf8");for(const required of [/garantia legal/i,/vício/i,/reparo/i,/correção/i,/reexecu/i,/responsabilidade do prestador/i,/boa-fé/i,/proteção de dados/i])assert.match(customer,required);});
test("endereço exige CEP e UF, GPS é opcional e coordenadas são estritas",()=>{assert.equal(assertLocation(null),null);for(const location of [{consent:true,latitude:91,longitude:0},{consent:true,latitude:-91,longitude:0},{consent:true,latitude:0,longitude:181},{consent:true,latitude:0,longitude:-181},{consent:true,latitude:"-19",longitude:-43},{consent:true,latitude:null,longitude:0},{consent:true,latitude:NaN,longitude:0},{consent:true,latitude:Infinity,longitude:0}])assert.throws(()=>assertLocation(location),/INVALID_LOCATION/);const html=fs.readFileSync(path.join(root,"web/index.html"),"utf8");assert.match(html,/select name="state" required/);assert.equal((html.match(/<option value="[A-Z]{2}">/g)||[]).length,27);assert.match(html,/name="postalCode" required/);});
test("branding oficial e contato aprovado permanecem referenciados",()=>{const html=fs.readFileSync(path.join(root,"web/index.html"),"utf8");assert.match(html,/assets\/brand\/reforma-profissional-logo\.svg/);assert.match(html,/5531990102500/);assert.match(fs.readFileSync(path.join(root,"vercel.json"),"utf8"),/^((?!redirects).)*$/s);});
