"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),{execFileSync}=require("node:child_process");
const root=path.resolve(__dirname,".."),registry=require("../server/legal-document-registry"),authority=require("../server/contract-authority"),{validateUpload}=require("../server/private-file-storage"),{signSession}=require("../server/auth"),{createHandler:createAcceptanceHandler}=require("../api/legal-acceptances"),{verifySignature}=require("../server/mercado-pago-webhook"),{advanceQuote}=require("../domain/quote-workflow"),{transitionOrderStatus,createOrder,resetIdempotencyForTests}=require("../domain/order-engine");
const secret="test-session-secret-more-than-thirty-two-bytes";
function response(){return{statusCode:0,body:null,status(n){this.statusCode=n;return this},json(v){this.body=v;return v}}}
test("HTML legal routes are responsive, correctly mapped and raw Markdown is not published",()=>{execFileSync(process.execPath,["scripts/build-web.js"],{cwd:root});const client=fs.readFileSync(path.join(root,"dist/termos/cliente/index.html"),"utf8"),provider=fs.readFileSync(path.join(root,"dist/termos/prestador/index.html"),"utf8");assert.match(client,/customer-service-terms-v1/);assert.doesNotMatch(client,/provider-service-agreement-v1/);assert.match(provider,/provider-service-agreement-v1/);assert.doesNotMatch(provider,/customer-service-terms-v1/);assert.match(client,/id="legal-accept" type="checkbox"/);assert.match(client,/id="legal-continue"[^>]+disabled/);assert.equal(fs.existsSync(path.join(root,"dist/docs/customer-service-terms-v1.md")),false);assert.match(fs.readFileSync(path.join(root,"dist/public/legal/legal.css"),"utf8"),/font:18px\/1\.7/);});
test("official legal hashes are computed from approved server files",()=>{for(const type of registry.DOCUMENT_TYPES){const doc=registry.resolveLegalDocument(type),expected=crypto.createHash("sha256").update(fs.readFileSync(doc.documentPath)).digest("hex");assert.equal(doc.officialHash,expected);assert.match(doc.officialHash,/^[a-f0-9]{64}$/);}});
test("browser hashes and stale versions cannot control an acceptance",()=>{const accepted=authority.accept({documentType:"CLIENT_TERMS",subjectId:"C-1",accepted:true,displayedDocumentVersion:"customer-service-terms-v1",documentHash:"0".repeat(64)});assert.equal(accepted.documentHash,registry.resolveLegalDocument("CLIENT_TERMS").officialHash);assert.equal(accepted.documentType,"CLIENT_TERMS");assert.throws(()=>authority.accept({documentType:"CLIENT_TERMS",subjectId:"C-1",accepted:true,displayedDocumentVersion:"old"}),/STALE/);});
test("authenticated acceptance uses session subject and rejects forged controlled fields",async()=>{const handler=createAcceptanceHandler({repository:{async create(v){return v}},secretValue:secret}),token=signSession({sub:"C-9",role:"CUSTOMER"},{secretValue:secret});let res=response();await handler({method:"POST",headers:{authorization:`Bearer ${token}`},body:{accepted:true,documentType:"CLIENT_TERMS",displayedDocumentVersion:"customer-service-terms-v1"}},res);assert.equal(res.statusCode,201);assert.equal(res.body.subjectId,"C-9");res=response();await handler({method:"POST",headers:{authorization:`Bearer ${token}`},body:{accepted:true,documentType:"CLIENT_TERMS",documentHash:"forged"}},res);assert.equal(res.statusCode,400);});
test("private upload validates bytes, MIME, extension and PDF purpose",()=>{const png=Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,1]);assert.equal(validateUpload({bytes:png,mimeType:"image/png",originalName:"foto.png",purpose:"ORDER_PROBLEM"}).mimeType,"image/png");assert.throws(()=>validateUpload({bytes:Buffer.from("MZ executable"),mimeType:"image/png",originalName:"x.png",purpose:"ORDER_PROBLEM"}),/UNSAFE/);assert.throws(()=>validateUpload({bytes:Buffer.from("%PDF-1.7"),mimeType:"application/pdf",originalName:"x.pdf",purpose:"ORDER_PROBLEM"}),/PDF_NOT_ALLOWED/);});
test("QUOTE and order status machines reject premature or invalid execution",()=>{assert.throws(()=>advanceQuote("CUSTOMER_APPROVED","SERVICE_STARTED","PROVIDER"),/INVALID/);resetIdempotencyForTests();const order=createOrder({customerId:"c",serviceId:"s",category:"c",description:"d"},"state-final");assert.throws(()=>transitionOrderStatus(order,"SERVICE_STARTED","PROVIDER"),/Transição inválida/);});
test("Mercado Pago webhook signature rejects tampering",()=>{const ts=Math.floor(Date.now()/1000),requestId="req",dataId="123",secretValue="webhook-secret",manifest=`id:${dataId};request-id:${requestId};ts:${ts};`,v1=crypto.createHmac("sha256",secretValue).update(manifest).digest("hex");assert.equal(verifySignature({signature:`ts=${ts},v1=${v1}`,requestId,dataId,secret:secretValue}),true);assert.equal(verifySignature({signature:`ts=${ts},v1=${"0".repeat(64)}`,requestId,dataId,secret:secretValue}),false);});
test("production web source has no fictitious metrics, provider, raw legal Markdown or operational localStorage",()=>{const html=fs.readFileSync(path.join(root,"web/index.html"),"utf8"),js=fs.readFileSync(path.join(root,"web/app.js"),"utf8");for(const value of ["João Técnico","328 atendimentos","25 min","IA simulada","/docs/customer-service-terms-v1.md"])assert.equal(html.includes(value),false,value);assert.equal(/localStorage/.test(html+js),false);});
test("PWA excludes APIs and sensitive routes and cache version was advanced",()=>{const sw=fs.readFileSync(path.join(root,"sw.js"),"utf8");assert.match(sw,/v16-production-fix/);assert.match(sw,/pathname\.startsWith\("\/api\/"\)/);assert.match(sw,/admin\|finance\|private\|antecedentes\|sessao/);});
