"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,"..");
const app=require("../config/app-config"),{handleDeepLink}=require("../mobile/deep-links"),{NativeLocationAdapter,SOURCES}=require("../mobile/location-adapter"),{createPushAdapter,validatePushEvent,NOTIFICATION_EVENTS}=require("../mobile/push-adapter");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");

test("identidade e ambientes iOS ficam centralizados",()=>{assert.equal(app.iosBundleId,"br.com.reformaprofissional.app");assert.equal(app.androidApplicationId,"br.com.reformaprofissional.app");assert.equal(app.iosBuildNumber,"1");assert.equal(app.getEnvironment("production").loggingLevel,"warn");});
test("deep links têm roteamento seguro cross-platform",()=>{assert.equal(handleDeepLink("https://www.reformaprofissional.com.br/solicitar-servico/",{platform:"IOS"}).type,"SERVICE_REQUEST");assert.equal(handleDeepLink("https://www.reformaprofissional.com.br/pedido/OS_123",{platform:"ANDROID"}).id,"OS_123");assert.equal(handleDeepLink("https://www.reformaprofissional.com.br/oportunidade/42",{platform:"PWA"}).type,"PROVIDER_OPPORTUNITY");assert.equal(handleDeepLink("https://www.reformaprofissional.com.br/pagamento/sucesso",{platform:"WEB"}).type,"PAYMENT_RESULT");assert.equal(handleDeepLink("https://evil.example/pedido/1").reason,"UNTRUSTED_ORIGIN");});
test("Universal Links preservam rotas e bundle id por template",()=>{const aasa=JSON.parse(read("public/.well-known/apple-app-site-association"));assert.match(aasa.applinks.details[0].appIDs[0],/APP_BUNDLE_ID$/);assert.deepEqual(aasa.applinks.details[0].components.map(item=>item["/"]),["/solicitar-servico/","/pedido/*"]);});
test("mensagens iOS são claras e não pedem background location",()=>{const plist=read("ios/App/App/Info.plist.template");for(const key of ["NSLocationWhenInUseUsageDescription","NSCameraUsageDescription","NSPhotoLibraryUsageDescription","NSUserNotificationsUsageDescription"])assert.match(plist,new RegExp(key));assert.doesNotMatch(plist,/AlwaysUsageDescription|AlwaysAndWhenInUse/);});
test("adapter iOS captura uma vez e normaliza",async()=>{const adapter=new NativeLocationAdapter({platform:"ios",getCurrentPosition:async()=>({coords:{latitude:-19.92,longitude:-43.94,accuracy:8},timestamp:1})});const result=await adapter.captureOnce({consent:true});assert.deepEqual(SOURCES,["IOS_NATIVE","ANDROID_NATIVE","WEB_GEOLOCATION","MANUAL_ADDRESS","GEOCODED_ADDRESS"]);assert.equal(result.locationSource,"IOS_NATIVE");assert.equal(result.accuracyMeters,8);assert.ok(result.capturedAt);await assert.rejects(()=>adapter.captureOnce(),/Consentimento/);});
test("push suporta os três canais e eventos operacionais",()=>{assert.equal(createPushAdapter("web").channel,"WEB_PUSH");assert.equal(createPushAdapter("android").channel,"ANDROID_PUSH");assert.equal(createPushAdapter("ios").channel,"IOS_PUSH");for(const event of ["NEW_PROVIDER_OFFER","OFFER_EXPIRING","PROVIDER_ACCEPTED","PROVIDER_EN_ROUTE","PROVIDER_ARRIVED","SERVICE_STARTED","ADDITIONAL_QUOTE","SERVICE_COMPLETED","PAYMENT_CONFIRMED","PAYOUT_RELEASED"])assert.equal(validatePushEvent(event),event);assert.ok(NOTIFICATION_EVENTS.length>=10);});
test("safe areas e teclado mobile estão protegidos",()=>{const css=read("styles.css");for(const inset of ["safe-area-inset-top","safe-area-inset-bottom","safe-area-inset-left","safe-area-inset-right"])assert.match(css,new RegExp(inset));assert.match(css,/scroll-margin-bottom/);assert.match(css,/position:sticky/);});
test("PWA, Android, Web e integrações preservadas",()=>{assert.ok(fs.existsSync(path.join(root,"manifest.webmanifest")));assert.match(read("package.json"),/sync:android/);assert.match(read("index.html"),/viewport-fit=cover/);assert.match(read("app.js"),/5531990102500/);assert.match(read("app.js"),/AW-17424041657\/Rb7QCI780u4cELmNt_RA/);assert.match(read("app.js"),/popularServices/);});
