"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm");
function load(){const elements={};for(const id of ["get-location","location-status"]){elements[id]={textContent:"",disabled:false}}const fields={};for(const name of ["address","number","neighborhood","city","postalCode","latitude","longitude","locationAccuracy","locationTimestamp"]){fields[name]={value:"",focus(){this.focused=true}}}elements["request-form"]=fields;const context={module:{exports:{}},exports:{},document:{querySelector:s=>elements[s.slice(1)],querySelectorAll:()=>[]},navigator:{},fetch(){},URL,Intl,globalThis:null};context.globalThis=context;vm.runInNewContext(fs.readFileSync("web/app.js","utf8"),context);return {app:context.module.exports,elements,fields};}
const position={coords:{latitude:-19.9,longitude:-43.9,accuracy:8},timestamp:0};
function gps(success=true){return {getCurrentPosition(resolve,reject){success?resolve(position):reject(new Error("denied"));}}}
function response(body,ok=true){return {ok,json:async()=>body};}
test("permissão aceita preenche rua, bairro e cidade",async()=>{const h=load();assert.equal(await h.app.requestCurrentLocation({geolocation:gps(),fetchImpl:async()=>response({address:"Rua A",number:"10",neighborhood:"Centro",city:"BH",postalCode:"30000-000"})}),true);assert.equal(h.fields.address.value,"Rua A");assert.equal(h.fields.neighborhood.value,"Centro");assert.equal(h.fields.city.value,"BH");assert.equal(h.elements["get-location"].textContent,"✓ Localização encontrada");assert.equal(h.elements["get-location"].disabled,false);});
test("permissão negada mantém formulário manual utilizável",async()=>{const h=load();h.fields.address.value="Manual";assert.equal(await h.app.requestCurrentLocation({geolocation:gps(false),fetchImpl:async()=>response({})}),false);assert.equal(h.fields.address.value,"Manual");assert.match(h.elements["location-status"].textContent,/Digite o endereço/);assert.equal(h.elements["get-location"].textContent,"Tentar localização novamente");});
test("timeout usa o mesmo fallback e reabilita botão",async()=>{const h=load();const timeout={getCurrentPosition(resolve,reject){reject({code:3})}};await h.app.requestCurrentLocation({geolocation:timeout});assert.equal(h.elements["get-location"].disabled,false);assert.match(h.elements["location-status"].textContent,/Digite o endereço/);});
test("navegador sem geolocation permite preenchimento manual",async()=>{const h=load();assert.equal(await h.app.requestCurrentLocation({geolocation:null}),false);h.fields.city.value="Betim";assert.equal(h.fields.city.value,"Betim");});
test("falha de reverse geocode não conserva coordenadas",async()=>{const h=load();await h.app.requestCurrentLocation({geolocation:gps(),fetchImpl:async()=>response({},false)});assert.equal(h.fields.latitude.value,"");assert.equal(h.fields.longitude.value,"");});
test("resultado parcial preenche disponível, deixa número vazio e o foca",async()=>{const h=load();await h.app.requestCurrentLocation({geolocation:gps(),fetchImpl:async()=>response({address:"Av. A",neighborhood:"Funcionários",city:"BH"})});assert.equal(h.fields.number.value,"");assert.equal(h.fields.number.focused,true);assert.equal(h.fields.neighborhood.value,"Funcionários");assert.equal(h.fields.city.value,"BH");});
