"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,".."),{signSession}=require("../server/auth"),{createProvider}=require("../server/provider-onboarding"),{adminHandler}=require("../server/operations-api"),{createHandler:createProviderHandler}=require("../server/provider-api"),{createHandler:createEvidenceHandler}=require("../api/evidence"),{MemoryOrderRepository}=require("../server/order-repository"),{RedisPrivateFileStorage}=require("../server/private-file-storage");
const secret="document-review-tests-secret-at-least-32",base={fullName:"Pessoa Teste",professionalName:"Profissional",cpf:"52998224725",rg:"MG123456",rgIssuer:"SSP",rgState:"MG",phone:"31999999999",email:"p@example.test",password:"senha-segura-123",address:{postalCode:"30140071",street:"Rua A",number:"1",neighborhood:"Centro",city:"Belo Horizonte",state:"MG"},specialties:["ELETRICISTA"],contractAccepted:true,truthDeclaration:true,documents:{PROFILE_PHOTO:"E-P",RG_FRONT:"E-F",RG_BACK:"E-B",CPF_DOCUMENT:"E-C",BACKGROUND_CHECK:"E-A",ADDRESS_PROOF:"E-E"}};
function response(){return{statusCode:0,headers:{},setHeader(k,v){this.headers[k]=v},status(v){this.statusCode=v;return this},json(v){this.body=v;return v},end(v){this.body=v}}}async function invoke(handler,{method="GET",token,query={},body,headers={}}={}){const res=response();await handler({method,query,body,headers:{...headers,...token?{authorization:`Bearer ${token}`}:{}} ,socket:{remoteAddress:"127.0.0.1"}},res);return res}
test("cadastro mantém RG frente/verso consecutivos e comprovante como último upload",()=>{const html=fs.readFileSync(path.join(root,"prestador/cadastro/index.html"),"utf8"),names=[...html.matchAll(/name="(PROFILE_PHOTO|RG_FRONT|RG_BACK|CPF_DOCUMENT|BACKGROUND_CHECK|ADDRESS_PROOF)"/g)].map(x=>x[1]);assert.deepEqual(names,["PROFILE_PHOTO","RG_FRONT","RG_BACK","CPF_DOCUMENT","BACKGROUND_CHECK","ADDRESS_PROOF"]);assert.match(html,/identity-document[\s\S]*RG_FRONT[\s\S]*RG_BACK/)});
test("contrato construído tem cabeçalho e versão únicos e aceite desmarcado",()=>{require("node:child_process").execFileSync(process.execPath,["scripts/build-web.js"],{cwd:root});const html=fs.readFileSync(path.join(root,"dist/termos/prestador/index.html"),"utf8");assert.equal((html.match(/<h1>CONTRATO DE INTERMEDIAÇÃO E PRESTAÇÃO DE SERVIÇOS — PRESTADOR<\/h1>/g)||[]).length,1);assert.equal((html.match(/<strong>Versão:<\/strong>/g)||[]).length,1);assert.match(html,/id="legal-accept" type="checkbox"/);assert.doesNotMatch(html,/id="legal-accept"[^>]+checked/)});
test("registro persiste somente evidenceId e aceite oficial versionado",async()=>{let stored;const repository={async create(value){stored=value}},storage={async put({ownerId,purpose}){return{evidenceId:`E-${purpose}-${ownerId.slice(0,3)}`}}},documentUploads=Object.fromEntries(Object.keys(base.documents).map(type=>[type,{originalName:type==="PROFILE_PHOTO"?"x.jpg":"x.pdf",mimeType:type==="PROFILE_PHOTO"?"image/jpeg":"application/pdf",base64:"AA=="}]));const res=await invoke(createProviderHandler({repository,storage}),{method:"POST",query:{route:"register"},body:{...base,documents:undefined,documentUploads,displayedDocumentVersion:"provider-service-agreement-v1"}});assert.equal(res.statusCode,201);assert.ok(Object.values(stored.documents).every(doc=>doc.evidenceId&&!doc.base64));assert.equal(stored.contract.version,"provider-service-agreement-v1");assert.equal(stored.contract.officialHash.length,64);assert.match(stored.contract.acceptanceEvidenceId,/^ACE-/)});
test("assessor lista, detalha e revisa, mas não toma decisão final",async()=>{const repository=new MemoryOrderRepository(),provider=createProvider(base,{providerId:"PRV-1"});await repository.saveProvider(provider);const token=signSession({sub:"REV-1",role:"REGISTRATION_REVIEWER"},{secretValue:secret});let res=await invoke(adminHandler({repository,secretValue:secret}),{token,query:{route:"providers"}});assert.equal(res.statusCode,200);res=await invoke(adminHandler({repository,secretValue:secret}),{token,query:{route:"provider",id:"PRV-1"}});assert.equal(res.statusCode,200);res=await invoke(adminHandler({repository,secretValue:secret}),{method:"POST",token,query:{id:"PRV-1",action:"start-review"},body:{}});assert.equal(res.statusCode,200);res=await invoke(adminHandler({repository,secretValue:secret}),{method:"POST",token,query:{id:"PRV-1",action:"approve"},body:{}});assert.equal(res.statusCode,403)});
test("listagem e detalhe negam usuário não autorizado",async()=>{const repository=new MemoryOrderRepository(),token=signSession({sub:"FIN",role:"FINANCE"},{secretValue:secret});for(const route of ["providers","provider"]){const res=await invoke(adminHandler({repository,secretValue:secret}),{token,query:{route,id:"PRV"}});assert.equal(res.statusCode,403)}});
test("antecedente bruto é negado a admin, assessor e financeiro e permitido a compliance",async()=>{const record={evidenceId:"E-BG",ownerId:"PRV-1",purpose:"BACKGROUND_CHECK",mimeType:"application/pdf",payload:Buffer.from("%PDF-x").toString("base64")},storage=Object.create(RedisPrivateFileStorage.prototype);storage.command=async()=>JSON.stringify(record);for(const role of ["ADMIN","REGISTRATION_REVIEWER","FINANCE"]){const token=signSession({sub:role,role},{secretValue:secret}),res=await invoke(createEvidenceHandler({storage,secretValue:secret}),{token,query:{id:"E-BG"}});assert.equal(res.statusCode,role==="FINANCE"?403:403)}const token=signSession({sub:"CMP",role:"ADMIN_COMPLIANCE"},{secretValue:secret}),res=await invoke(createEvidenceHandler({storage,secretValue:secret}),{token,query:{id:"E-BG"}});assert.equal(res.statusCode,200)});
test("detalhe mascara identificadores, ordena documentos e oculta evidência de antecedentes",()=>{const detail=require("../server/provider-review-service").adminDetail(createProvider(base));assert.notEqual(detail.cpf,base.cpf);assert.notEqual(detail.rg,base.rg);assert.deepEqual(Object.keys(detail.documents),["PROFILE_PHOTO","RG_FRONT","RG_BACK","CPF_DOCUMENT","BACKGROUND_CHECK","ADDRESS_PROOF"]);assert.equal(detail.documents.BACKGROUND_CHECK.evidenceId,null)});
test("build contém as três rotas e nenhum arquivo documental",()=>{for(const route of ["prestador/cadastro/index.html","admin/prestadores/index.html","termos/prestador/index.html"])assert.ok(fs.existsSync(path.join(root,"dist",route)));const files=[];for(const dirent of fs.readdirSync(path.join(root,"dist"),{recursive:true,withFileTypes:true}))if(dirent.isFile())files.push(dirent.name);assert.equal(files.some(name=>/\.(pdf|docx?)$/i.test(name)),false)});
