"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {MemoryOrderRepository}=require("../server/order-repository"),{createProvider,eligibility,publicProjection}=require("../server/provider-onboarding"),reviews=require("../server/provider-review-service"),{createHandler:createProviderHandler}=require("../server/provider-api"),{adminHandler}=require("../server/operations-api"),{reviewHandler}=require("../server/compliance-service"),{signSession}=require("../server/auth"),{createHandler:createPostalHandler}=require("../api/geocode/reverse");
const secret="provider-e2e-secret-at-least-32-characters",admin={sub:"ADM-1",role:"ADMIN"};
const input={fullName:"Profissional de Teste",professionalName:"Teste Elétrica",cpf:"52998224725",rg:"MG-12.345.678",rgIssuer:"SSP",rgState:"MG",phone:"31999999999",email:"provider@example.test",password:"senha-de-teste-segura",address:{postalCode:"30140071",street:"Rua Teste",number:"10",neighborhood:"Centro",city:"Belo Horizonte",state:"MG"},specialties:["ELETRICISTA"],contractAccepted:true,documents:{RG_FRONT:"E-RG",CPF_DOCUMENT:"E-CPF",ADDRESS_PROOF:"E-ADDR",PROFILE_PHOTO:"E-PHOTO",BACKGROUND_CHECK:"E-BG"}};
function response(){return{statusCode:0,headers:{},body:null,setHeader(k,v){this.headers[k]=v},status(value){this.statusCode=value;return this},json(value){this.body=value;return value},end(value){this.body=value}}}
async function invoke(handler,{method="GET",token,query={},body}={}){const res=response();await handler({method,query,body,headers:token?{authorization:`Bearer ${token}`}:{},socket:{remoteAddress:"127.0.0.1"}},res);return res;}
async function prepared(){const repository=new MemoryOrderRepository(),provider=createProvider(input,{providerId:"PRV-E2E"});await repository.saveProvider(provider);return repository;}

test("provider correction lifecycle reaches APPROVED and matching only after every gate",async()=>{const repository=await prepared(),adminToken=signSession(admin,{secretValue:secret}),providerToken=signSession({sub:"PRV-E2E",role:"PROVIDER"},{secretValue:secret}),complianceToken=signSession({sub:"CMP-1",role:"ADMIN_COMPLIANCE"},{secretValue:secret});
 for(const status of ["DRAFT","SUBMITTED","UNDER_REVIEW","DOCUMENTS_REQUIRED","SUSPENDED"]){const record=await repository.getProvider("PRV-E2E");Object.assign(record,{status,active:status!=="SUSPENDED",availability:"AVAILABLE"});await repository.saveProvider(record);assert.equal(eligibility(record,{category:"ELETRICISTA"}).eligible,false,status)}
 let record=await repository.getProvider("PRV-E2E");Object.assign(record,{status:"SUBMITTED",onboardingStatus:"SUBMITTED",active:true});await repository.saveProvider(record);
 let res=await invoke(adminHandler({repository,secretValue:secret}),{method:"POST",token:adminToken,query:{id:"PRV-E2E",action:"start-review"},body:{}});assert.equal(res.statusCode,200);assert.equal(res.body.provider.status,"UNDER_REVIEW");
 res=await invoke(adminHandler({repository,secretValue:secret}),{method:"POST",token:adminToken,query:{id:"PRV-E2E",action:"request-correction"},body:{documentType:"RG_FRONT",reasonCode:"ILLEGIBLE",message:"Envie uma foto legível."}});assert.equal(res.body.provider.status,"DOCUMENTS_REQUIRED");
 const storage={async put(){return{evidenceId:"E-RG-NEW",mimeType:"image/png",size:20,createdAt:new Date().toISOString()}}};res=await invoke(createProviderHandler({repository,storage,secretValue:secret}),{method:"POST",token:providerToken,query:{route:"documents",id:"RG_FRONT"},body:{originalName:"rg.png",mimeType:"image/png",base64:"AA=="}});assert.equal(res.body.providerStatus,"RESUBMITTED");record=await repository.getProvider("PRV-E2E");assert.equal(record.documents.RG_FRONT.history[0].evidenceId,"E-RG");assert.equal(reviews.providerSelfProjection(record).correctionRequests.length,0);
 await reviews.mutate(repository,"PRV-E2E",admin,"START_REVIEW");for(const type of ["RG_FRONT","CPF_DOCUMENT","ADDRESS_PROOF","PROFILE_PHOTO"])await reviews.mutate(repository,"PRV-E2E",admin,"VALIDATE_DOCUMENT",{documentType:type});
 res=await invoke(reviewHandler({repository,secretValue:secret}),{method:"POST",token:complianceToken,query:{id:"PRV-E2E"},body:{decision:"VALIDATE",reasonCode:"VERIFIED"}});assert.equal(res.body.status,"VALIDATED");record=await reviews.mutate(repository,"PRV-E2E",admin,"APPROVE");record.availability="AVAILABLE";await repository.saveProvider(record);assert.equal(eligibility(record,{category:"ELETRICISTA"}).eligible,true);assert.equal(record.status,"APPROVED");assert.ok(record.adminAudit.every(event=>event.actorId&&event.actorRole&&event.action&&event.providerId&&event.timestamp));});

test("RBAC and projections keep sensitive provider data private",async()=>{const repository=await prepared(),finance=signSession({sub:"FIN-1",role:"FINANCE"},{secretValue:secret}),customer=signSession({sub:"CUS-1",role:"CUSTOMER"},{secretValue:secret}),provider2=signSession({sub:"OTHER",role:"PROVIDER"},{secretValue:secret});let res=await invoke(adminHandler({repository,secretValue:secret}),{token:finance,query:{route:"provider",id:"PRV-E2E"}});assert.equal(res.statusCode,403);res=await invoke(adminHandler({repository,secretValue:secret}),{token:customer,query:{route:"provider",id:"PRV-E2E"}});assert.equal(res.statusCode,403);res=await invoke(createProviderHandler({repository,secretValue:secret}),{token:provider2,query:{route:"me"}});assert.equal(res.statusCode,404);const provider=await repository.getProvider("PRV-E2E"),publicView=publicProjection({...provider,status:"APPROVED"});assert.equal(JSON.stringify(publicView).includes(provider.cpf),false);assert.equal(JSON.stringify(publicView).includes(provider.rg),false);assert.equal(JSON.stringify(publicView).includes("Rua Teste"),false);assert.equal(JSON.stringify(publicView).includes("adminAudit"),false);});

test("postal-code endpoint normalizes a fake provider and fails with manual fallback",async()=>{const found=createPostalHandler({postalCodeLookup:async()=>({postalCode:"30140071",street:"Avenida Afonso Pena",neighborhood:"Centro",city:"Belo Horizonte",state:"MG"})});let res=await invoke(found,{query:{postalCode:"30140-071"}});assert.equal(res.statusCode,200);assert.equal(res.body.city,"Belo Horizonte");const unavailable=createPostalHandler({postalCodeLookup:async()=>{throw Object.assign(new Error("down"),{statusCode:502})}});res=await invoke(unavailable,{query:{postalCode:"30140071"}});assert.equal(res.statusCode,502);assert.match(res.body.error,/Preencha manualmente/);});

test("admin list/detail are filtered, masked and reject attendant access",async()=>{const repository=await prepared(),adminToken=signSession(admin,{secretValue:secret}),attendant=signSession({sub:"ATT-1",role:"ATTENDANT"},{secretValue:secret});let res=await invoke(adminHandler({repository,secretValue:secret}),{token:adminToken,query:{route:"providers",status:"SUBMITTED"}});assert.equal(res.body.providers.length,1);assert.equal("cpf" in res.body.providers[0],false);res=await invoke(adminHandler({repository,secretValue:secret}),{token:adminToken,query:{route:"provider",id:"PRV-E2E"}});assert.equal(res.body.provider.cpf,"***.982.247-**");assert.notEqual(res.body.provider.rg,input.rg);assert.equal("passwordHash" in res.body.provider,false);res=await invoke(adminHandler({repository,secretValue:secret}),{token:attendant,query:{route:"provider",id:"PRV-E2E"}});assert.equal(res.statusCode,403);});
