"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{execFileSync}=require("node:child_process");
const {catalog,CATALOG_VERSION}=require("../catalog"),candidate=require("../catalog-v5-candidate"),{MemoryOrderRepository}=require("../server/order-repository"),{createCustomerOrder}=require("../server/order-service"),{signSession}=require("../server/auth"),{adminHandler,financeHandler}=require("../server/privileged-api"),financial=require("../domain/financial-engine");
const root=path.resolve(__dirname,".."),secret="test-only-session-secret-that-is-at-least-32-bytes";
const input=code=>({serviceCode:code,description:"Teste seguro",address:{street:"Rua A",number:"1",neighborhood:"Centro",city:"Belo Horizonte"},urgency:"Hoje",materialMode:"NONE",customer:{name:"Cliente",whatsapp:"31999999999"},customerPriceCents:100,providerPercent:99,pricingSnapshot:{forged:true}});
function response(){return{statusCode:0,body:null,status(n){this.statusCode=n;return this},json(v){this.body=v;return v}}}
async function call(handler,{token,method="GET"}={}){const res=response(),req={method,headers:token?{authorization:`Bearer ${token}`}:{}};await handler(req,res);return res;}
test("public build is an explicit allowlist without private financial modules, symbols or source maps",()=>{execFileSync(process.execPath,["scripts/build-web.js"],{cwd:root});const files=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);e.isDirectory()?walk(p):files.push(p)}}walk(path.join(root,"dist"));const rel=files.map(f=>path.relative(path.join(root,"dist"),f));for(const forbidden of ["catalog-financial.js","domain/financial-engine.js","services/pricing-engine.js","repositories/interfaces.js","adapters/gestao-click-adapter.js"])assert(!rel.includes(forbidden),forbidden);assert.equal(rel.some(f=>f.endsWith(".map")),false);const text=files.filter(f=>/\.(js|html|json|webmanifest)$/.test(f)).map(f=>fs.readFileSync(f,"utf8")).join("\n");for(const symbol of ["FINANCIAL_CATALOG","providerMinimumPayoutCents","providerFinalPayoutCents","platformGrossRevenueCents","contributionMarginCents","taxRateBasisPoints","customerAcquisitionCostCents","adminApproval","approvedBy","approvalReason","TaxProfileRepository","FinancialSnapshotRepository","catalog-financial"])assert.equal(text.includes(symbol),false,symbol);});
test("service worker never pre-caches or runtime-caches internal server modules",()=>{const sw=fs.readFileSync(path.join(root,"sw.js"),"utf8");for(const value of ["domain/","services/pricing-engine","repositories/","adapters/gestao-click","catalog-financial","financial-engine"])assert.equal(sw.includes(value),false,value);});
test("V4 stays exact and V5 remains an unpublished draft",()=>{assert.equal(CATALOG_VERSION,"RMBH-2026-09-v4");assert.equal(catalog.length,89);assert.equal(candidate.CANDIDATE_VERSION,"RMBH-2026-09-v5-candidate");assert.equal(candidate.CANDIDATE_STATUS,"DRAFT");assert.equal(candidate.approved,false);assert.equal(candidate.effectiveDate,null);assert.equal(catalog.some(s=>s.code.startsWith("V5C")),false);});
test("server resolves official FIXED price and ignores forged browser financial values",async()=>{const repository=new MemoryOrderRepository();const {order,publicView}=await createCustomerOrder(input("RP0001"),{repository,idempotencyKey:"fixed-1"});assert.equal(order.pricingSnapshot.customerPriceCents,15000);assert.equal(publicView.price.amountCents,15000);assert.equal("pricingSnapshot" in publicView,false);for(const key of ["providerPercent","providerFinalPayoutCents","contributionMarginCents"])assert.equal(key in publicView,false);});
test("QUOTE is created without browser price, fictitious price or snapshot",async()=>{const repository=new MemoryOrderRepository();const {order,publicView}=await createCustomerOrder(input("RP0012"),{repository,idempotencyKey:"quote-1"});assert.equal(order.pricingMode,"QUOTE");assert.equal(order.pricingSnapshot,null);assert.equal(publicView.price,null);});
test("provider projection never contains customer price",()=>{const snapshot=financial.createFinancialSnapshot({customerPriceCents:15000,catalogVersion:CATALOG_VERSION,taxProfile:{taxProfileId:"T",taxRegime:"OUTRO",taxBaseType:"PLATFORM_REVENUE_ONLY",taxRateBasisPoints:0,effectiveFrom:"2026-01-01",source:"TEST",approvedBy:"TEST",approvedAt:"2026-01-01",version:"1"}});const view=financial.providerFinancialView(snapshot);assert.equal("customerPriceCents" in view,false);assert.equal("customerFinalTotalCents" in view,false);});
test("admin endpoint enforces server-side authentication and RBAC",async()=>{const repository=new MemoryOrderRepository(),handler=adminHandler({repository,secretValue:secret});assert.equal((await call(handler)).statusCode,401);for(const role of ["CUSTOMER","PROVIDER","ATTENDANT","FINANCE"]){const token=signSession({sub:"u",role},{secretValue:secret});assert.equal((await call(handler,{token})).statusCode,403,role)}const token=signSession({sub:"admin",role:"ADMIN"},{secretValue:secret});assert.equal((await call(handler,{token})).statusCode,200);});
test("finance endpoint is finance-only and a browser role edit cannot grant access",async()=>{const repository=new MemoryOrderRepository(),handler=financeHandler({repository,secretValue:secret});const admin=signSession({sub:"a",role:"ADMIN"},{secretValue:secret});assert.equal((await call(handler,{token:admin})).statusCode,403);const finance=signSession({sub:"f",role:"FINANCE"},{secretValue:secret});assert.equal((await call(handler,{token:finance})).statusCode,200);const [h,p,s]=finance.split('.'),claims=JSON.parse(Buffer.from(p,'base64url'));claims.role="ADMIN";claims.permissions=["ADMIN_READ"];const forged=`${h}.${Buffer.from(JSON.stringify(claims)).toString('base64url')}.${s}`;assert.equal((await call(adminHandler({repository,secretValue:secret}),{token:forged})).statusCode,401);});
test("expired server session is rejected",async()=>{const repository=new MemoryOrderRepository(),handler=adminHandler({repository,secretValue:secret});const expired=signSession({sub:"a",role:"ADMIN"},{secretValue:secret,now:1,ttlSeconds:1});assert.equal((await call(handler,{token:expired})).statusCode,401);});
test("production boundaries fail closed without private configuration",()=>{const oldSecret=process.env.AUTH_SESSION_SECRET,oldUrl=process.env.KV_REST_API_URL,oldToken=process.env.KV_REST_API_TOKEN;delete process.env.AUTH_SESSION_SECRET;delete process.env.KV_REST_API_URL;delete process.env.KV_REST_API_TOKEN;try{assert.throws(()=>signSession({sub:"a",role:"ADMIN"}),/NOT_CONFIGURED/);const {RedisOrderRepository}=require("../server/order-repository");assert.throws(()=>new RedisOrderRepository(),/NOT_CONFIGURED/);}finally{if(oldSecret)process.env.AUTH_SESSION_SECRET=oldSecret;if(oldUrl)process.env.KV_REST_API_URL=oldUrl;if(oldToken)process.env.KV_REST_API_TOKEN=oldToken;}});
