"use strict";

/** Catálogo oficial unificado de mão de obra para Belo Horizonte e RMBH. */
const CATALOG_VERSION = "RMBH-2026-09-v7-launch";
const CATALOG_EFFECTIVE_DATE = "2026-09-21";
const CATALOG_RELEASE = Object.freeze({ version: CATALOG_VERSION, effectiveDate: CATALOG_EFFECTIVE_DATE, reason: "Migração explícita V4 → V7 Launch: preços psicológicos e serviços aprovados", actor: "ADMIN:REFORMA_PROFISSIONAL" });
const SERVICE_SCOPE_NOTES = Object.freeze({
  "RP0010": "Instalação simples no quadro existente. Novo circuito ou alteração relevante exige orçamento adicional.",
  "RP0012": "Curto-circuito exige diagnóstico e orçamento antes da execução.",
  "RP0013": "Diagnóstico e revisão básica do circuito. Correções adicionais dependem de aprovação.",
  "RP0014": "Instalação simples em ponto existente. Torneira e materiais não inclusos. Adaptações hidráulicas exigem orçamento adicional.",
  "RP0019": "Desentupimento residencial simples. Máquina especializada, hidrojato ou problema na coluna de esgoto exige orçamento.",
  "RP0020": "Desentupimento residencial simples. Problemas em coluna ou rede de esgoto exigem orçamento.",
  "RP0022": "Troca em ponto existente. Mecanismo e demais materiais não inclusos.",
  "RP0023": "Vazamento visível e acessível. Vazamento embutido ou caça-vazamento exige orçamento separado.",
  "RP0025": "Instalação em pontos hidráulico e elétrico existentes. Adaptações exigem orçamento.",
  "RP0026": "Registro acessível. Quebra de parede ou revestimento exige orçamento adicional.",
  "RP0027": "Instalação em ponto existente. Vaso, acessórios e materiais não inclusos.",
  "RP0029": "Gabinete pronto em ponto existente. Alteração hidráulica exige orçamento.",
  "RP0030": "Suporte fornecido pelo cliente. Parede especial, drywall, TV muito grande ou instalação complexa pode exigir adicional aprovado.",
  "RP0034": "Espelho pequeno ou médio fornecido pelo cliente. Espelhos grandes ou especiais exigem orçamento.",
  "RP0038": "Guarda-roupa convencional. Modelos muito grandes, portas de correr complexas, embutidos ou desmontagem e remontagem exigem orçamento adicional.",
  "RP0041": "Troca convencional. Dobradiça e demais ferragens não inclusas.",
  "RP0042": "Somente mão de obra para troca convencional. Fechadura fornecida pelo cliente.",
  "RP0043": "Fechadura convencional. Fechadura digital ou eletrônica exige outro serviço ou orçamento.",
  "RP0044": "Reparo simples e acessível. Reparos estruturais maiores exigem orçamento.",
  "RP0045": "Porta interna convencional, com folha e ferragens fornecidas pelo cliente. Alteração de vão, marco ou alvenaria exige orçamento.",
  "RP0046": "Instalação padrão de split de até 9.000/12.000 BTU em infraestrutura compatível. Tubulação, material, trabalho em altura e adaptações são cobrados separadamente.",
  "RP0048": "Manutenção e diagnóstico corretivo básico. Peças e materiais não inclusos.",
  "RP0049": "Exige diagnóstico de refrigerante, quantidade, BTUs, vazamento e reparos antes do orçamento.",
  "RP0050": "Instalação padrão com infraestrutura pronta. Duto, furação estrutural ou adaptação exige orçamento.",
  "RP0051": "Nicho e ponto preparados. Alterações de bancada, gás ou elétrica exigem orçamento.",
  "RP0052": "Exige diagnóstico de circuito, tensão, disjuntor e cabeamento antes do orçamento.",
  "RP0054": "Preço depende de metragem, preparação, demãos, altura, tinta e estado da superfície.",
  "RP0055": "Preço depende de metragem, preparação, demãos, altura, tinta e estado da superfície.",
  "RP0056": "Mão de obra para uma porta padrão em condição normal. Lixamento pesado ou reparo exige adicional ou orçamento.",
  "RP0057": "Preço depende de metragem, preparação, demãos, altura, tinta e estado da superfície."
});
const rawCatalog = [
  { code: "RP0001", name: "Instalação de tomada simples", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 14990 },
  { code: "RP0002", name: "Troca de tomada", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 10990 },
  { code: "RP0003", name: "Instalação de interruptor", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 13990 },
  { code: "RP0004", name: "Troca de interruptor", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 9990 },
  { code: "RP0005", name: "Instalação de luminária", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 14990 },
  { code: "RP0006", name: "Troca de luminária", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 11990 },
  { code: "RP0007", name: "Instalação de chuveiro elétrico", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 13990 },
  { code: "RP0008", name: "Troca de resistência de chuveiro", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 9990 },
  { code: "RP0009", name: "Instalação de ventilador de teto", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 17990 },
  { code: "RP0010", name: "Instalação de disjuntor", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 24990 },
  { code: "RP0011", name: "Troca de disjuntor", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 17990 },
  { code: "RP0012", name: "Reparo em curto-circuito", category: "ELÉTRICA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0013", name: "Revisão elétrica de circuito", category: "ELÉTRICA", pricingMode: "FIXED", customerPriceCents: 17990 },
  { code: "RP0014", name: "Instalação simples de torneira em ponto existente", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 14990 },
  { code: "RP0015", name: "Troca de torneira simples", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 9990 },
  { code: "RP0016", name: "Reparo de torneira pingando", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 12990 },
  { code: "RP0017", name: "Instalação de sifão", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 11990 },
  { code: "RP0018", name: "Troca de sifão", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 10990 },
  { code: "RP0019", name: "Desentupimento simples de pia", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 19990 },
  { code: "RP0020", name: "Desentupimento de vaso sanitário", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 22990 },
  { code: "RP0021", name: "Reparo em descarga", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 15990 },
  { code: "RP0022", name: "Troca de mecanismo de descarga", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 18990 },
  { code: "RP0023", name: "Reparo de vazamento interno simples", category: "HIDRÁULICA", pricingMode: "FROM", customerPriceCents: 19990 },
  { code: "RP0024", name: "Instalação de filtro de água", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 11990 },
  { code: "RP0025", name: "Instalação de máquina de lavar", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 15990 },
  { code: "RP0026", name: "Troca de registro", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 17990 },
  { code: "RP0027", name: "Instalação de vaso sanitário", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 31990 },
  { code: "RP0028", name: "Vedação de vaso sanitário", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 17990 },
  { code: "RP0029", name: "Instalação de gabinete de banheiro", category: "HIDRÁULICA", pricingMode: "FIXED", customerPriceCents: 24990 },
  { code: "RP0030", name: "Instalação de suporte de TV", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 15990 },
  { code: "RP0031", name: "Instalação de prateleira", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 11990 },
  { code: "RP0032", name: "Instalação de varal", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 11990 },
  { code: "RP0033", name: "Instalação de cortina ou persiana", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 13990 },
  { code: "RP0034", name: "Instalação de espelho", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 13990 },
  { code: "RP0035", name: "Fixação de quadro", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 7990 },
  { code: "RP0036", name: "Montagem de mesa", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 14990 },
  { code: "RP0037", name: "Montagem de móvel pequeno", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 14990 },
  { code: "RP0038", name: "Montagem de guarda-roupa", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 27990 },
  { code: "RP0039", name: "Montagem de cômoda", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 17990 },
  { code: "RP0040", name: "Regulagem de porta de armário", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 11990 },
  { code: "RP0041", name: "Troca de dobradiça", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 12990 },
  { code: "RP0042", name: "Troca de fechadura", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 14990 },
  { code: "RP0043", name: "Instalação de fechadura", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 17990 },
  { code: "RP0044", name: "Reparo em porta de madeira", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 24990 },
  { code: "RP0045", name: "Instalação de porta", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "FIXED", customerPriceCents: 44990 },
  { code: "RP0046", name: "Instalação de ar-condicionado split", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "FIXED", customerPriceCents: 69990 },
  { code: "RP0047", name: "Limpeza completa de ar-condicionado", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "FROM", customerPriceCents: 24990 },
  { code: "RP0048", name: "Manutenção completa de ar-condicionado", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0049", name: "Carga de gás de ar-condicionado", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0050", name: "Instalação de coifa", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "FIXED", customerPriceCents: 24990 },
  { code: "RP0051", name: "Instalação de cooktop", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "FIXED", customerPriceCents: 21990 },
  { code: "RP0052", name: "Instalação de forno elétrico", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0053", name: "Instalação de depurador", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "FIXED", customerPriceCents: 19990 },
  { code: "RP0054", name: "Pintura de parede interna", category: "PINTURA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0055", name: "Pintura de teto", category: "PINTURA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0056", name: "Pintura de porta", category: "PINTURA", pricingMode: "FIXED", customerPriceCents: 19990 },
  { code: "RP0057", name: "Pintura de grade", category: "PINTURA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0058", name: "Pintura residencial completa", category: "PINTURA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0059", name: "Pintura externa", category: "PINTURA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0060", name: "Aplicação de textura", category: "PINTURA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0061", name: "Correção de infiltração", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0062", name: "Impermeabilização de área", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0063", name: "Reparo de reboco", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0064", name: "Assentamento de piso", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0065", name: "Assentamento de porcelanato", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0066", name: "Reforma de banheiro", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0067", name: "Reforma de cozinha", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0068", name: "Reforma de apartamento", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0069", name: "Reforma de casa", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0070", name: "Construção de parede de alvenaria", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0071", name: "Demolição de parede", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0072", name: "Execução de contrapiso", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0073", name: "Instalação de revestimento", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0074", name: "Reparo estrutural", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0075", name: "Instalação de drywall", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0076", name: "Forro de gesso", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0077", name: "Sanca de gesso", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0078", name: "Reparo em telhado", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0079", name: "Troca de telhas", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0080", name: "Instalação de calha", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0081", name: "Limpeza de calha", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0082", name: "Construção de telhado", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0083", name: "Serviço de serralheria", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0084", name: "Instalação de portão", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0085", name: "Serviço de vidraçaria", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0086", name: "Instalação de box", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0087", name: "Paisagismo", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0088", name: "Poda de árvore", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "RP0089", name: "Reforma geral sob medida", category: "REFORMA E CONSTRUÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7H001", name: "Instalação de torneira com criação/adaptação hidráulica", category: "HIDRÁULICA", pricingMode: "FROM", customerPriceCents: 19990, referenceMaximumPriceCents: 24990 },
  { code: "V7H002", name: "Desentupimento completo de pia", category: "HIDRÁULICA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7H003", name: "Desentupimento simples de esgoto", category: "HIDRÁULICA", pricingMode: "FROM", customerPriceCents: 24990 },
  { code: "V7H004", name: "Desentupimento completo de esgoto", category: "HIDRÁULICA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7H005", name: "Reparo de vazamento externo completo", category: "HIDRÁULICA", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7H006", name: "Instalação de registro e mangueira GLP", category: "HIDRÁULICA", pricingMode: "QUOTE", customerPriceCents: null, qualifiedProfessionalRequired: true },
  { code: "V7M001", name: "Instalação de esquadria de alumínio", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7M002", name: "Instalação de telhado retrátil", category: "MONTAGEM E INSTALAÇÃO", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7L001", name: "Diarista até 4h", category: "LIMPEZA", pricingMode: "FIXED", customerPriceCents: 17990, pricingPolicy: { optionsCents: [14990,17990,19990], selectedBy: "ADMIN_SERVICE_AREA_POLICY" } },
  { code: "V7L002", name: "Diarista diária", category: "LIMPEZA", pricingMode: "FIXED", customerPriceCents: 24990 },
  { code: "V7L003", name: "Limpeza pós-obra", category: "LIMPEZA", pricingMode: "FROM", customerPriceCents: 29990, referenceMaximumPriceCents: 49990, priceVariables: ["metragem","nível de sujeira","ambientes","resíduos","equipamentos","acesso","profissionais"] },
  { code: "V7C001", name: "Limpeza evaporadora", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "FROM", customerPriceCents: 14990 },
  { code: "V7C002", name: "Limpeza condensadora", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "FROM", customerPriceCents: 14990 },
  { code: "V7C003", name: "Manutenção evaporadora", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7C004", name: "Manutenção condensadora", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7C005", name: "Manutenção corretiva", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7C006", name: "Infraestrutura / linha frigorígena de cobre", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null, priceVariables: ["metragem","diâmetro","BTU","altura","dreno","elétrica","canaleta","acesso"] },
  { code: "V7C007", name: "Pacote simples — 1 unidade", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7C008", name: "Pacote duplo — 2 unidades", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7C009", name: "Pacote triplo — 3 unidades", category: "CLIMATIZAÇÃO E EQUIPAMENTOS", pricingMode: "QUOTE", customerPriceCents: null },
  { code: "V7P001", name: "Pintura simples", category: "PINTURA", pricingMode: "QUOTE", customerPriceCents: null, priceVariables: ["metragem","preparação","lixamento","massa","selador","demãos","complexidade","acabamento"] },
  { code: "V7P002", name: "Laqueamento", category: "PINTURA", pricingMode: "QUOTE", customerPriceCents: null }
];

const catalog = Object.freeze(rawCatalog.map(service => Object.freeze({
  serviceCode: service.code,
  serviceName: service.name,
  code: service.code,
  name: service.name,
  category: service.category,
  pricingMode: service.pricingMode,
  customerPriceCents: service.customerPriceCents,
  scopeNotes: SERVICE_SCOPE_NOTES[service.code] || service.scopeNotes || (service.pricingMode === "FIXED" ? "Mão de obra no escopo padrão descrito pelo serviço. Materiais e adaptações não inclusos; exceções exigem orçamento adicional." : undefined),
  materialsIncluded: false,
  exclusions: Object.freeze([]),
  catalogVersion: CATALOG_VERSION,
  referenceMaximumPriceCents: service.referenceMaximumPriceCents,
  pricingPolicy: service.pricingPolicy ? Object.freeze(service.pricingPolicy) : undefined,
  priceVariables: service.priceVariables ? Object.freeze(service.priceVariables) : undefined,
  qualifiedProfessionalRequired: service.qualifiedProfessionalRequired === true,
  comboEligible: ["RP0002", "RP0004", "RP0031", "RP0033", "RP0035", "RP0040"].includes(service.code)
})));

function getServiceByCode(code) {
  return catalog.find(service => service.code === code) || null;
}

const api = Object.freeze({ catalog, getServiceByCode, CATALOG_VERSION, CATALOG_EFFECTIVE_DATE, CATALOG_RELEASE });
if (typeof module !== "undefined" && module.exports) module.exports = api;
if (typeof globalThis !== "undefined") globalThis.ReformaProfissionalCatalog = api;
