"use strict";
const crypto=require("node:crypto");
const TIERS=Object.freeze({STANDARD:60,TECHNICAL:65,SPECIALIST:70,CUSTOM:null});
const ECONOMIC_STATUSES=Object.freeze(["HEALTHY","LOW_MARGIN","BREAK_EVEN","NEGATIVE","REVIEW_REQUIRED"]);
const TAX_REGIMES=Object.freeze(["SIMPLES_NACIONAL","LUCRO_PRESUMIDO","OUTRO"]);
const TAX_BASE_TYPES=Object.freeze(["PLATFORM_REVENUE_ONLY","GROSS_TRANSACTION_VALUE"]);
const n=(v=0,k="value")=>{if(!Number.isInteger(v)||v<0)throw new TypeError(`${k} must be non-negative integer cents`);return v};
function deepFreeze(v){if(v&&typeof v==="object"&&!Object.isFrozen(v)){Reflect.ownKeys(v).forEach(k=>deepFreeze(v[k]));Object.freeze(v)}return v}
function stableStringify(v){if(Array.isArray(v))return`[${v.map(stableStringify)}]`;if(v&&typeof v==="object")return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stableStringify(v[k])}`)}}`;return JSON.stringify(v)}
function snapshotHash(s){const copy={...s};delete copy.snapshotHash;return crypto.createHash("sha256").update(stableStringify(copy)).digest("hex")}
function tierOf(i){const providerTier=i.providerTier||i.tier||(i.providerPercent!==undefined?"CUSTOM":"STANDARD");if(!(providerTier in TIERS))throw Error("INVALID_PROVIDER_TIER");const providerPercent=providerTier==="CUSTOM"?i.providerPercent:TIERS[providerTier];if(!Number.isFinite(providerPercent)||providerPercent<0||providerPercent>100)throw Error("INVALID_PROVIDER_PERCENT");if(providerTier==="CUSTOM"&&providerPercent>70){if(i.adminApproval!==true)throw Error("CUSTOM acima de 70% exige aprovação Admin");if(!i.approvedBy||!i.approvedAt||!i.approvalReason)throw Error("CUSTOM_APPROVAL_AUDIT_REQUIRED")}return{providerTier,providerPercent,adminApproval:i.adminApproval===true,approvedBy:i.approvedBy||null,approvedAt:i.approvedAt||null,approvalReason:i.approvalReason||null}}
function taxOf(p){if(!p||!["taxProfileId","taxRegime","taxBaseType","taxRateBasisPoints","effectiveFrom","source","approvedBy","approvedAt","version"].every(k=>p[k]!==undefined&&p[k]!==null&&p[k]!==""))throw Error("INVALID_TAX_PROFILE");if(!TAX_REGIMES.includes(p.taxRegime)||!TAX_BASE_TYPES.includes(p.taxBaseType)||!Number.isInteger(p.taxRateBasisPoints)||p.taxRateBasisPoints<0)throw Error("INVALID_TAX_PROFILE");return p}
function status(m,r,review){if(review)return"REVIEW_REQUIRED";const b=n(r.breakEvenToleranceCents||0),t=n(r.targetContributionMarginCents||0);return m< -b?"NEGATIVE":m<=b?"BREAK_EVEN":m<t?"LOW_MARGIN":"HEALTHY"}
/* O tratamento fiscal definitivo da Reforma Profissional depende de validação da contabilidade. O motor suporta simulação; ele não determina sozinho a obrigação tributária real. */
function createFinancialSnapshot(i){
 const customerPriceCents=n(i.customerPriceCents,"customerPriceCents"),laborAmountCents=n(i.laborAmountCents??customerPriceCents),materialCostCents=n(i.materialCostCents||0),materialSaleCents=n(i.materialSaleCents||0),discountCents=n(i.discountCents||0),cashbackUsedCents=n(i.cashbackUsedCents||0),customerFinalTotalCents=n(i.customerFinalTotalCents??laborAmountCents+materialSaleCents-discountCents-cashbackUsedCents);const t=tierOf(i);
 const providerCalculatedPayoutCents=Math.round(laborAmountCents*t.providerPercent/100),providerMinimumPayoutCents=n(i.providerMinimumPayoutCents||0),providerFinalPayoutCents=Math.max(providerCalculatedPayoutCents,providerMinimumPayoutCents),travelBonusCents=n(i.travelBonusCents||0),urgencyBonusCents=n(i.urgencyBonusCents||0),scarcityBonusCents=n(i.scarcityBonusCents||0),providerTotalReceivableCents=providerFinalPayoutCents+travelBonusCents+urgencyBonusCents+scarcityBonusCents,platformGrossRevenueCents=laborAmountCents-providerFinalPayoutCents;
 const tax=taxOf(i.taxProfile),taxBaseCents=tax.taxBaseType==="PLATFORM_REVENUE_ONLY"?platformGrossRevenueCents:customerFinalTotalCents,taxEstimateCents=Math.round(taxBaseCents*tax.taxRateBasisPoints/10000);
 const paymentFeeCents=n(i.paymentFeeCents??i.paymentFeesCents??0),customerAcquisitionCostCents=n(i.customerAcquisitionCostCents??i.cacCents??0),supportCostCents=n(i.supportCostCents||0),warrantyReserveCents=n(i.warrantyReserveCents||0),travelSubsidyCents=n(i.travelSubsidyCents||0),cashbackCostCents=n(i.cashbackCostCents||0),refundReserveCents=n(i.refundReserveCents||0),otherVariableCostsCents=n(i.otherVariableCostsCents??i.taxesCents??0),materialPartnerRevenueCents=n(i.materialPartnerRevenueCents||0);
 const contributionMarginCents=platformGrossRevenueCents-taxEstimateCents-paymentFeeCents-customerAcquisitionCostCents-supportCostCents-warrantyReserveCents-travelSubsidyCents-cashbackCostCents-refundReserveCents-otherVariableCostsCents+materialPartnerRevenueCents,r=i.financialRules||{},review=providerFinalPayoutCents>providerCalculatedPayoutCents&&contributionMarginCents<(r.minimumMarginAfterPayoutFloorCents||0),estimatedTravelMinutes=n(i.estimatedTravelMinutes||0),estimatedServiceMinutes=n(i.estimatedServiceMinutes||0),mins=estimatedTravelMinutes+estimatedServiceMinutes,estimatedProviderHourlyEarningCents=mins?Math.round(providerTotalReceivableCents*60/mins):0,minimumProviderHourlyEarningCents=n(i.minimumProviderHourlyEarningCents||0),providerStatus=estimatedProviderHourlyEarningCents<minimumProviderHourlyEarningCents?"UNATTRACTIVE":"ATTRACTIVE";
 const s={pricingPolicyVersion:i.pricingPolicyVersion||"financial-policy-v1",catalogVersion:i.catalogVersion,serviceCode:i.serviceCode||null,serviceName:i.serviceName||null,category:i.category||null,pricingMode:i.pricingMode||"FIXED",customerPriceCents,laborAmountCents,materialCostCents,materialSaleCents,discountCents,cashbackUsedCents,customerFinalTotalCents,materialsIncluded:i.materialsIncluded===true,scopeNotes:i.scopeNotes||null,exclusions:i.exclusions||[],...t,providerCalculatedPayoutCents,providerMinimumPayoutCents,providerFinalPayoutCents,providerTotalReceivableCents,travelBonusCents,urgencyBonusCents,scarcityBonusCents,platformPercent:100-t.providerPercent,platformGrossRevenueCents,taxProfileId:tax.taxProfileId,taxRegime:tax.taxRegime,taxBaseType:tax.taxBaseType,taxRateBasisPoints:tax.taxRateBasisPoints,taxBaseCents,taxEstimateCents,paymentFeeCents,customerAcquisitionCostCents,supportCostCents,warrantyReserveCents,travelSubsidyCents,cashbackCostCents,refundReserveCents,otherVariableCostsCents,materialPartnerRevenueCents,contributionMarginCents,contributionMarginPercent:platformGrossRevenueCents?Math.round(contributionMarginCents*10000/platformGrossRevenueCents)/100:0,economicStatus:status(contributionMarginCents,r,review),estimatedTravelDistanceKm:i.estimatedTravelDistanceKm||0,estimatedTravelMinutes,estimatedServiceMinutes,estimatedProviderHourlyEarningCents,minimumProviderHourlyEarningCents,providerStatus,attractivenessActions:providerStatus==="UNATTRACTIVE"?["NEAREST_PROVIDER","TRAVEL_BONUS","URGENCY_BONUS"]:[],platformMinimumContributionCents:n(i.platformMinimumContributionCents||0),marketStatus:"COMPETITIVE",financialRecommendation:review?"MANUAL_PRICE_REVIEW":"KEEP",createdAt:i.createdAt||new Date().toISOString()};
 Object.assign(s,{tier:s.providerTier,providerPayoutCents:providerFinalPayoutCents,providerBasePayoutCents:providerCalculatedPayoutCents,providerTotalPayoutCents:providerTotalReceivableCents,variableCostsCents:taxEstimateCents+paymentFeeCents+customerAcquisitionCostCents+supportCostCents+warrantyReserveCents+travelSubsidyCents+cashbackCostCents+refundReserveCents+otherVariableCostsCents,platformStatus:contributionMarginCents<0?"UNVIABLE":contributionMarginCents<s.platformMinimumContributionCents?"LOW_MARGIN":"VIABLE",alerts:review?["MANUAL_PRICE_REVIEW"]:[]});s.snapshotHash=snapshotHash(s);return deepFreeze(s)
}
function pick(s,f){return deepFreeze(Object.fromEntries(f.map(k=>[k,s[k]])))}
const customerFinancialView=s=>pick(s,["serviceCode","serviceName","category","pricingMode","laborAmountCents","materialSaleCents","discountCents","cashbackUsedCents","customerFinalTotalCents","materialsIncluded","scopeNotes","exclusions","catalogVersion"]);
const providerFinancialView=s=>pick(s,["serviceCode","serviceName","scopeNotes","estimatedTravelDistanceKm","estimatedTravelMinutes","estimatedServiceMinutes","providerFinalPayoutCents","travelBonusCents","urgencyBonusCents","scarcityBonusCents","providerTotalReceivableCents"]);
const INTERNAL=["customerPriceCents","customerFinalTotalCents","providerTier","providerPercent","providerCalculatedPayoutCents","providerMinimumPayoutCents","providerFinalPayoutCents","providerTotalReceivableCents","platformPercent","platformGrossRevenueCents","taxProfileId","taxRegime","taxBaseType","taxRateBasisPoints","taxBaseCents","taxEstimateCents","paymentFeeCents","customerAcquisitionCostCents","supportCostCents","warrantyReserveCents","travelSubsidyCents","cashbackCostCents","refundReserveCents","otherVariableCostsCents","materialPartnerRevenueCents","contributionMarginCents","contributionMarginPercent","economicStatus"];
const adminFinancialView=s=>pick(s,["serviceCode","serviceName",...INTERNAL]),financeFinancialView=s=>pick(s,["serviceCode","serviceName","pricingPolicyVersion","catalogVersion","snapshotHash",...INTERNAL]);
function attendantFinancialView(s,p=[]){const f=["customerPriceCents","customerFinalTotalCents","pricingMode","scopeNotes"];if(p.includes("CAN_VIEW_PROVIDER_PAYOUT"))f.push("providerFinalPayoutCents","providerTotalReceivableCents");if(p.includes("CAN_VIEW_PLATFORM_MARGIN"))f.push(...INTERNAL.filter(x=>!f.includes(x)));return pick(s,f)}
function validateFinancialSnapshot(s){const req=["pricingPolicyVersion","catalogVersion","customerPriceCents","providerTier","providerFinalPayoutCents","taxProfileId","taxBaseType","taxEstimateCents","contributionMarginCents","economicStatus","createdAt","snapshotHash"];if(!s||req.some(k=>s[k]===undefined||s[k]===null)||!ECONOMIC_STATUSES.includes(s.economicStatus)||snapshotHash(s)!==s.snapshotHash)throw Error("INVALID_FINANCIAL_SNAPSHOT");return true}
module.exports={TIERS,ECONOMIC_STATUSES,TAX_REGIMES,TAX_BASE_TYPES,deepFreeze,stableStringify,snapshotHash,createFinancialSnapshot,customerFinancialView,providerFinancialView,attendantFinancialView,adminFinancialView,financeFinancialView,validateFinancialSnapshot};
