"use strict";
const {getServiceByCode}=require("../catalog");
const TIERS=Object.freeze({STANDARD:60,TECHNICAL:65,SPECIALIST:70});
const ADJUSTMENTS=Object.freeze(["KEEP","LOWER_CUSTOMER_PRICE","RAISE_CUSTOMER_PRICE","RAISE_PROVIDER_PAYOUT","ADD_TRAVEL_BONUS","ADD_SCARCITY_BONUS","REQUIRES_MANUAL_REVIEW"]);
const cents=value=>{if(!Number.isInteger(value)||value<0)throw new TypeError("Valores devem ser centavos inteiros não negativos.");return value;};
function createPricingSnapshot(input){const customerPriceCents=cents(input.customerPriceCents);const percent=input.providerPercent??TIERS[input.tier||"STANDARD"];if(percent>70&&!input.adminApproved)throw new Error("Participação acima de 70% exige aprovação Admin.");if(percent<0||percent>100)throw new RangeError("Percentual inválido.");const providerBasePayoutCents=Math.round(customerPriceCents*percent/100);const travelBonusCents=cents(input.travelBonusCents||0),urgencyBonusCents=cents(input.urgencyBonusCents||0),scarcityBonusCents=cents(input.scarcityBonusCents||0);const providerTotalPayoutCents=providerBasePayoutCents+travelBonusCents+urgencyBonusCents+scarcityBonusCents;const costs=["cacCents","paymentFeesCents","taxesCents","supportCostCents","warrantyReserveCents","travelSubsidyCents","refundReserveCents","otherVariableCostsCents"].reduce((s,k)=>s+cents(input[k]||0),0);const platformGrossRevenueCents=customerPriceCents-providerBasePayoutCents;const contributionMarginCents=customerPriceCents-providerTotalPayoutCents-costs;const marketStatus=customerPriceCents>(input.marketMaxCents??Infinity)?"ABOVE_MARKET":customerPriceCents>(input.maximumCompetitivePriceCents??Infinity)?"ATTENTION":"COMPETITIVE";const minimum=input.platformMinimumContributionCents||0;const platformStatus=contributionMarginCents<0?"UNVIABLE":contributionMarginCents<minimum?"LOW_MARGIN":"VIABLE";const minutes=(input.estimatedServiceMinutes||0)+(input.estimatedTravelMinutes||0);return Object.freeze({...input,tier:input.tier||"STANDARD",providerPercent:percent,marketMinCents:input.marketMinCents,marketAverageCents:input.marketAverageCents,marketMaxCents:input.marketMaxCents,customerRecommendedPriceCents:input.customerRecommendedPriceCents,maximumCompetitivePriceCents:input.maximumCompetitivePriceCents,providerMinimumPayoutCents:input.providerMinimumPayoutCents,platformMinimumContributionCents:minimum,customerPriceCents,providerBasePayoutCents,travelBonusCents,urgencyBonusCents,scarcityBonusCents,providerTotalPayoutCents,estimatedProviderHourlyEarningCents:minutes?Math.round(providerTotalPayoutCents*60/minutes):0,platformGrossRevenueCents,variableCostsCents:costs,contributionMarginCents,marketStatus,platformStatus,alerts:providerTotalPayoutCents<(input.providerMinimumPayoutCents||0)?["PROVIDER_PAYOUT_TOO_LOW"]:[],createdAt:new Date().toISOString()});}
function recommendPricingAdjustment(s){if(s.providerPercent>70)return"REQUIRES_MANUAL_REVIEW";if(s.customerPriceCents>s.maximumCompetitivePriceCents)return"LOWER_CUSTOMER_PRICE";if(s.providerTotalPayoutCents<s.providerMinimumPayoutCents)return s.scarcityLevel&&["HIGH","CRITICAL"].includes(s.scarcityLevel)?"ADD_SCARCITY_BONUS":"RAISE_PROVIDER_PAYOUT";if(s.contributionMarginCents<s.platformMinimumContributionCents)return s.customerPriceCents<s.maximumCompetitivePriceCents?"RAISE_CUSTOMER_PRICE":"REQUIRES_MANUAL_REVIEW";return"KEEP";}
function createCatalogPricingSnapshot(code,input={}){const service=getServiceByCode(code);if(!service)throw new Error(`Serviço de catálogo não encontrado: ${code}`);if(service.pricingMode==="QUOTE")throw new Error(`Serviço ${code} exige orçamento antes da precificação.`);return createPricingSnapshot({...input,serviceCode:service.code,tier:service.tier,customerPriceCents:service.customerPriceCents});}
module.exports={TIERS,ADJUSTMENTS,createPricingSnapshot,createCatalogPricingSnapshot,recommendPricingAdjustment};
