"use strict";
const crypto=require("node:crypto");
const ROLES=Object.freeze(["CUSTOMER","PROVIDER","ATTENDANT","ADMIN","FINANCE","ADMIN_COMPLIANCE","ADMIN_SECURITY"]);
const PERMISSIONS=Object.freeze({CUSTOMER:["ORDER_CREATE","OWN_ORDER_READ","OWN_FILE_WRITE","LEGAL_ACCEPT"],PROVIDER:["OWN_OFFER_READ","OWN_PAYOUT_READ","OWN_FILE_WRITE","OWN_FILE_READ","LEGAL_ACCEPT"],ATTENDANT:["OPERATIONS_READ"],ADMIN:["ADMIN_READ","ADMIN_WRITE"],FINANCE:["FINANCE_READ"],ADMIN_COMPLIANCE:["COMPLIANCE_DOCUMENT_READ"],ADMIN_SECURITY:["COMPLIANCE_DOCUMENT_READ"]});
const b64=v=>Buffer.from(v).toString("base64url");
function secret(value=process.env.AUTH_SESSION_SECRET){if(!value||value.length<32)throw new Error("AUTH_SESSION_SECRET_NOT_CONFIGURED");return value;}
function signSession(claims,{secretValue,now=Math.floor(Date.now()/1000),ttlSeconds=900}={}){if(!ROLES.includes(claims.role)||!claims.sub)throw new TypeError("INVALID_SESSION_CLAIMS");const header=b64(JSON.stringify({alg:"HS256",typ:"JWT"}));const payload=b64(JSON.stringify({sub:claims.sub,role:claims.role,permissions:claims.permissions||PERMISSIONS[claims.role],iat:now,exp:now+ttlSeconds}));const signature=crypto.createHmac("sha256",secret(secretValue)).update(`${header}.${payload}`).digest("base64url");return`${header}.${payload}.${signature}`;}
function verifySession(token,{secretValue,now=Math.floor(Date.now()/1000)}={}){if(typeof token!=="string")throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});const parts=token.split(".");if(parts.length!==3)throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});const expected=crypto.createHmac("sha256",secret(secretValue)).update(`${parts[0]}.${parts[1]}`).digest();let supplied;try{supplied=Buffer.from(parts[2],"base64url");}catch{supplied=Buffer.alloc(0)}if(supplied.length!==expected.length||!crypto.timingSafeEqual(supplied,expected))throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});let claims;try{claims=JSON.parse(Buffer.from(parts[1],"base64url"));}catch{throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401})}if(!ROLES.includes(claims.role)||!claims.sub||!Number.isInteger(claims.exp)||claims.exp<=now)throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});return Object.freeze(claims);}
function authorize(request,permission,options={}){const header=request.headers?.authorization||request.headers?.Authorization;if(!header?.startsWith("Bearer "))throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});const claims=verifySession(header.slice(7),options);if(!claims.permissions?.includes(permission))throw Object.assign(new Error("FORBIDDEN"),{statusCode:403});return claims;}
module.exports={ROLES,PERMISSIONS,signSession,verifySession,authorize};
