"use strict";
const crypto=require("node:crypto");
const ROLES=Object.freeze(["CUSTOMER","PROVIDER","ATTENDANT","ADMIN","FINANCE","ADMIN_COMPLIANCE","ADMIN_SECURITY"]);
const PERMISSIONS=Object.freeze({CUSTOMER:["ORDER_CREATE","OWN_ORDER_READ","OWN_FILE_WRITE","LEGAL_ACCEPT"],PROVIDER:["PROVIDER_OPERATE","OWN_OFFER_READ","OWN_PAYOUT_READ","OWN_FILE_WRITE","OWN_FILE_READ","LEGAL_ACCEPT"],ATTENDANT:["OPERATIONS_READ"],ADMIN:["ADMIN_READ","ADMIN_WRITE"],FINANCE:["FINANCE_READ","FISCAL_REVIEW"],ADMIN_COMPLIANCE:["COMPLIANCE_DOCUMENT_READ","COMPLIANCE_DOCUMENT_REVIEW"],ADMIN_SECURITY:["COMPLIANCE_DOCUMENT_READ","COMPLIANCE_DOCUMENT_REVIEW"]});
const b64=v=>Buffer.from(v).toString("base64url");
function secret(value=process.env.AUTH_SESSION_SECRET){if(!value||value.length<32)throw new Error("AUTH_SESSION_SECRET_NOT_CONFIGURED");return value;}
function signSession(claims,{secretValue,now=Math.floor(Date.now()/1000),ttlSeconds=900}={}){if(!ROLES.includes(claims.role)||!claims.sub)throw new TypeError("INVALID_SESSION_CLAIMS");const header=b64(JSON.stringify({alg:"HS256",typ:"JWT"}));const payload=b64(JSON.stringify({sub:claims.sub,role:claims.role,permissions:claims.permissions||PERMISSIONS[claims.role],iat:now,exp:now+ttlSeconds}));const signature=crypto.createHmac("sha256",secret(secretValue)).update(`${header}.${payload}`).digest("base64url");return`${header}.${payload}.${signature}`;}
function verifySession(token,{secretValue,now=Math.floor(Date.now()/1000)}={}){if(typeof token!=="string")throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});const parts=token.split(".");if(parts.length!==3)throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});const expected=crypto.createHmac("sha256",secret(secretValue)).update(`${parts[0]}.${parts[1]}`).digest();let supplied;try{supplied=Buffer.from(parts[2],"base64url");}catch{supplied=Buffer.alloc(0)}if(supplied.length!==expected.length||!crypto.timingSafeEqual(supplied,expected))throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});let claims;try{claims=JSON.parse(Buffer.from(parts[1],"base64url"));}catch{throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401})}if(!ROLES.includes(claims.role)||!claims.sub||!Number.isInteger(claims.exp)||claims.exp<=now)throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});return Object.freeze(claims);}
function authorize(request,permission,options={}){const header=request.headers?.authorization||request.headers?.Authorization,cookie=String(request.headers?.cookie||"").split(";").map(v=>v.trim()).find(v=>v.startsWith("rp_session=")),token=header?.startsWith("Bearer ")?header.slice(7):cookie?.slice("rp_session=".length);if(!token)throw Object.assign(new Error("UNAUTHENTICATED"),{statusCode:401});const claims=verifySession(token,options);if(!claims.permissions?.includes(permission))throw Object.assign(new Error("FORBIDDEN"),{statusCode:403});return claims;}
function passwordDigest(password,salt){return crypto.pbkdf2Sync(String(password),salt,210000,32,"sha256").toString("hex");}
function authenticateCredentials({username,password},{usersJson=process.env.AUTH_USERS_JSON}={}){let users;try{users=JSON.parse(usersJson||"");}catch{throw Object.assign(new Error("AUTH_NOT_CONFIGURED"),{statusCode:503});}const user=Array.isArray(users)?users.find(item=>item.username===username):null;if(!user||!ROLES.includes(user.role)||!user.subjectId||!user.salt||!user.passwordHash)throw Object.assign(new Error("INVALID_CREDENTIALS"),{statusCode:401});const actual=Buffer.from(passwordDigest(password,user.salt),"hex"),expected=Buffer.from(user.passwordHash,"hex");if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))throw Object.assign(new Error("INVALID_CREDENTIALS"),{statusCode:401});return{sub:user.subjectId,role:user.role};}
module.exports={ROLES,PERMISSIONS,signSession,verifySession,authorize,passwordDigest,authenticateCredentials};
