"use strict";
const crypto=require("node:crypto");
const QUOTE_FLOW=["CUSTOMER_REQUEST","PROVIDER_ANALYSIS","PROVIDER_QUOTE_SUBMITTED","PLATFORM_REVIEW","QUOTE_APPROVED","CUSTOMER_QUOTE_SENT","CUSTOMER_APPROVED","PROVIDER_AUTHORIZED","SERVICE_STARTED","SERVICE_COMPLETED"];
function fail(code,statusCode=409){throw Object.assign(new Error(code),{statusCode});}
function now(){return new Date().toISOString();}
function audit(order,event,actor,details={}){return{...order,auditTrail:[...(order.auditTrail||[]),{event,actor,timestamp:now(),...details}]};}
function assertOwner(order,providerId){if(order.providerId!==providerId)fail("FORBIDDEN",403);}
async function mutate(repository,id,fn){const order=await repository.get(id);if(!order)fail("ORDER_NOT_FOUND",404);const updated=fn(order);return repository.save(updated);}
async function assignProvider(repository,id,providerId,actor){const provider=await repository.getProvider(providerId);if(!provider)fail("PROVIDER_NOT_FOUND",404);if(provider.onboardingStatus!=="APPROVED")fail("PROVIDER_NOT_ELIGIBLE");return mutate(repository,id,o=>audit({...o,providerId,status:"OFFERED"},"PROVIDER_ASSIGNED",actor,{providerId}));}
async function providerAction(repository,id,providerId,action,body={}){return mutate(repository,id,order=>{assertOwner(order,providerId);const actor=`PROVIDER:${providerId}`;
  if(action==="accept"){if(order.status!=="OFFERED")fail("INVALID_ORDER_STATE");return audit({...order,status:"PROVIDER_ACCEPTED",quoteStatus:order.pricingMode==="QUOTE"?"PROVIDER_ANALYSIS":order.quoteStatus,quoteHistory:order.pricingMode==="QUOTE"?[...(order.quoteHistory||["CUSTOMER_REQUEST"]),"PROVIDER_ANALYSIS"]:order.quoteHistory},"PROVIDER_ACCEPTED",actor);}
  if(action==="decline"){if(order.status!=="OFFERED")fail("INVALID_ORDER_STATE");return audit({...order,providerId:null,status:"SEARCHING_PROVIDER"},"PROVIDER_DECLINED",actor);}
  if(action==="arrive"){if(order.status!=="PROVIDER_ACCEPTED")fail("INVALID_ORDER_STATE");return audit({...order,status:"PROVIDER_ARRIVED",providerArrivedAt:now()},"PROVIDER_ARRIVED",actor);}
  if(action==="start"){if(order.pricingMode==="QUOTE"&&order.quoteStatus!=="PROVIDER_AUTHORIZED")fail("PROVIDER_NOT_AUTHORIZED");if(!["PROVIDER_ACCEPTED","PROVIDER_ARRIVED"].includes(order.status))fail("INVALID_ORDER_STATE");return audit({...order,status:"SERVICE_STARTED",startedAt:now(),quoteStatus:order.pricingMode==="QUOTE"?"SERVICE_STARTED":order.quoteStatus,quoteHistory:order.pricingMode==="QUOTE"?[...order.quoteHistory,"SERVICE_STARTED"]:order.quoteHistory},"SERVICE_STARTED",actor);}
  if(action==="complete"){if(order.status!=="SERVICE_STARTED")fail("INVALID_ORDER_STATE");return audit({...order,status:"SERVICE_COMPLETED",completedAt:now(),quoteStatus:order.pricingMode==="QUOTE"?"SERVICE_COMPLETED":order.quoteStatus,quoteHistory:order.pricingMode==="QUOTE"?[...order.quoteHistory,"SERVICE_COMPLETED"]:order.quoteHistory,fiscalStatus:"FISCAL_DOCUMENT_REQUIRED"},"SERVICE_COMPLETED",actor);}
  if(action==="quote"){if(order.pricingMode!=="QUOTE"||order.quoteStatus!=="PROVIDER_ANALYSIS")fail("INVALID_QUOTE_STATE");if(!Number.isInteger(body.amountCents)||body.amountCents<=0)fail("INVALID_QUOTE_AMOUNT",400);return audit({...order,quoteStatus:"PROVIDER_QUOTE_SUBMITTED",quoteHistory:[...order.quoteHistory,"PROVIDER_QUOTE_SUBMITTED"],quote:{quoteId:`QTE-${crypto.randomUUID()}`,amountCents:body.amountCents,currency:"BRL",description:String(body.description||"").slice(0,1000),submittedAt:now()}},"PROVIDER_QUOTE_SUBMITTED",actor);}
  if(action==="fiscal-document"){if(order.status!=="SERVICE_COMPLETED"||!body.evidenceId||!body.type||!body.number||!body.date||!Number.isInteger(body.amountCents)||!body.issuer||!body.recipient)fail("INVALID_FISCAL_DOCUMENT",400);return audit({...order,fiscalStatus:"FISCAL_DOCUMENT_SUBMITTED",fiscalDocument:{type:body.type,number:body.number,date:body.date,amountCents:body.amountCents,issuer:body.issuer,recipient:body.recipient,evidenceId:body.evidenceId,submittedAt:now()}},"FISCAL_DOCUMENT_SUBMITTED",actor);}
  fail("UNKNOWN_ACTION",404);});}
async function adminAction(repository,id,action,body,claims){const actor=`${claims.role}:${claims.sub}`;return mutate(repository,id,order=>{
  if(action==="approve-quote"){if(order.quoteStatus!=="PROVIDER_QUOTE_SUBMITTED")fail("INVALID_QUOTE_STATE");return audit({...order,quoteStatus:"CUSTOMER_QUOTE_SENT",quoteHistory:[...order.quoteHistory,"PLATFORM_REVIEW","QUOTE_APPROVED","CUSTOMER_QUOTE_SENT"],quote:{...order.quote,reviewedAt:now(),reviewedBy:claims.sub}},"QUOTE_APPROVED_AND_SENT",actor,{transitions:["PLATFORM_REVIEW","QUOTE_APPROVED","CUSTOMER_QUOTE_SENT"]});}
  if(action==="authorize-service"){if(order.pricingMode==="QUOTE"&&order.quoteStatus!=="CUSTOMER_APPROVED")fail("CUSTOMER_APPROVAL_REQUIRED");return audit({...order,quoteStatus:order.pricingMode==="QUOTE"?"PROVIDER_AUTHORIZED":order.quoteStatus,quoteHistory:order.pricingMode==="QUOTE"?[...order.quoteHistory,"PROVIDER_AUTHORIZED"]:order.quoteHistory},"SERVICE_AUTHORIZED",actor);}
  if(action==="review-change-order"){if(order.changeOrder?.status!=="CHANGE_ORDER_CREATED")fail("INVALID_CHANGE_ORDER_STATE");const approved=body.decision==="APPROVE";return audit({...order,changeOrder:{...order.changeOrder,status:approved?"PLATFORM_REVIEW":"CUSTOMER_REJECTED",reviewedBy:claims.sub,reviewedAt:now()}},"CHANGE_ORDER_REVIEWED",actor);}
  fail("UNKNOWN_ACTION",404);});}
async function customerQuoteDecision(repository,id,customerId,decision){return mutate(repository,id,order=>{if(order.customerId!==customerId)fail("FORBIDDEN",403);if(order.quoteStatus!=="CUSTOMER_QUOTE_SENT")fail("INVALID_QUOTE_STATE");const approved=decision==="APPROVE",next=approved?"CUSTOMER_APPROVED":"CUSTOMER_REJECTED";return audit({...order,quoteStatus:next,quoteHistory:[...order.quoteHistory,next]},next,`CUSTOMER:${customerId}`);});}
async function createChangeOrder(repository,id,providerId,{amountCents,reason}){return mutate(repository,id,order=>{assertOwner(order,providerId);if(order.status!=="SERVICE_STARTED"||!Number.isInteger(amountCents)||amountCents<=0)fail("INVALID_CHANGE_ORDER",400);return audit({...order,changeOrder:{changeOrderId:`CHG-${crypto.randomUUID()}`,status:"CHANGE_ORDER_CREATED",amountCents,reason,createdAt:now()}},"CHANGE_ORDER_CREATED",`PROVIDER:${providerId}`);});}
async function customerChangeDecision(repository,id,customerId,decision){return mutate(repository,id,order=>{if(order.customerId!==customerId)fail("FORBIDDEN",403);if(order.changeOrder?.status!=="PLATFORM_REVIEW")fail("INVALID_CHANGE_ORDER_STATE");const approved=decision==="APPROVE";return audit({...order,changeOrder:{...order.changeOrder,status:approved?"APPLIED":"CUSTOMER_REJECTED",customerDecidedAt:now()},...(approved?{approvedAdditionalAmountCents:order.changeOrder.amountCents}:{})},approved?"CHANGE_ORDER_APPLIED":"CHANGE_ORDER_REJECTED",`CUSTOMER:${customerId}`);});}
async function reviewFiscal(repository,id,claims,{decision,reasonCode}){return mutate(repository,id,order=>{if(order.fiscalStatus!=="FISCAL_DOCUMENT_SUBMITTED")fail("INVALID_FISCAL_STATE");const approved=decision==="APPROVE";return audit({...order,fiscalStatus:approved?"FISCAL_DOCUMENT_APPROVED":"FISCAL_DOCUMENT_REJECTED",fiscalReview:{reviewedBy:claims.sub,reviewedAt:now(),decision:approved?"APPROVED":"REJECTED",reasonCode:reasonCode||null},...(approved?{providerPaymentStatus:"READY"}:{})},"FISCAL_DOCUMENT_REVIEWED",`${claims.role}:${claims.sub}`);});}
module.exports={QUOTE_FLOW,assignProvider,providerAction,adminAction,customerQuoteDecision,createChangeOrder,customerChangeDecision,reviewFiscal};
