"use strict";
const {authorize}=require("./auth"),{send,method,wrap}=require("./http"),ops=require("./operations-service"),{requestIdentity}=require("./rate-limit"),{publicOrderView}=require("./order-service");
function body(req){if(req.body&&typeof req.body==="object")return req.body;if(typeof req.body==="string")try{return JSON.parse(req.body)}catch{}throw Object.assign(new Error("INVALID_JSON_BODY"),{statusCode:400});}
function providerHandler({repository,secretValue,rateLimiter}={}){return wrap(async(req,res)=>{const claims=authorize(req,"PROVIDER_OPERATE",{secretValue}),route=req.query?.route||req.route,action=req.query?.action||req.action,id=req.query?.id||req.id;
  if(req.method==="GET"&&route==="profile"){const profile=await repository.getProvider(claims.sub);if(!profile)return send(res,404,{error:"PROVIDER_NOT_FOUND"});const {backgroundCheck,...safe}=profile;return send(res,200,{provider:safe,backgroundCheckStatus:backgroundCheck?.status||null});}
  if(req.method==="GET"&&route==="opportunities"){const orders=(await repository.list()).filter(o=>o.providerId===claims.sub&&o.status==="OFFERED");return send(res,200,{orders});}
  if(req.method==="GET"&&route==="orders"){const orders=(await repository.list()).filter(o=>o.providerId===claims.sub&&o.status!=="OFFERED");return send(res,200,{orders});}
  method(req,"POST");if(rateLimiter&&["quote","fiscal-document","background-check"].includes(action))await rateLimiter.assert({scope:`provider-${action}`,identity:requestIdentity(req,claims.sub),limit:10});
  if(action==="change-order")return send(res,200,{order:await ops.createChangeOrder(repository,id,claims.sub,body(req))});
  return send(res,200,{order:await ops.providerAction(repository,id,claims.sub,action,body(req))});});}
function adminHandler({repository,secretValue}={}){return wrap(async(req,res)=>{const claims=authorize(req,"ADMIN_READ",{secretValue}),route=req.query?.route||req.route,id=req.query?.id||req.id,action=req.query?.action||req.action;
  if(req.method==="GET"&&route==="orders")return send(res,200,{orders:await repository.list()});
  if(req.method==="GET"&&route==="providers")return send(res,200,{providers:(await repository.listProviders()).map(({backgroundCheck,...p})=>({...p,backgroundCheckStatus:backgroundCheck?.status||null}))});
  if(req.method==="GET"&&route==="provider"){const provider=await repository.getProvider(id);if(!provider)return send(res,404,{error:"PROVIDER_NOT_FOUND"});const {backgroundCheck,...safe}=provider;return send(res,200,{provider:safe,backgroundCheckStatus:backgroundCheck?.status||null});}
  authorize(req,"ADMIN_WRITE",{secretValue});method(req,"POST");const input=body(req);
  if(action==="assign-provider")return send(res,200,{order:await ops.assignProvider(repository,id,input.providerId,`ADMIN:${claims.sub}`)});
  if(["approve-quote","authorize-service","review-change-order"].includes(action))return send(res,200,{order:await ops.adminAction(repository,id,action,input,claims)});
  if(["approve","review"].includes(action)){const provider=await repository.getProvider(id);if(!provider)return send(res,404,{error:"PROVIDER_NOT_FOUND"});return send(res,200,{provider:await repository.saveProvider({...provider,onboardingStatus:action==="approve"?"APPROVED":"UNDER_REVIEW",reviewedBy:claims.sub,reviewedAt:new Date().toISOString()})});}
  throw Object.assign(new Error("UNKNOWN_ACTION"),{statusCode:404});});}
function customerHandler({repository,secretValue}={}){return wrap(async(req,res)=>{const claims=authorize(req,"OWN_ORDER_READ",{secretValue}),id=req.query?.id||req.id,order=await repository.get(id);if(!order)return send(res,404,{error:"ORDER_NOT_FOUND"});if(order.customerId!==claims.sub)throw Object.assign(new Error("FORBIDDEN"),{statusCode:403});if(req.method==="GET")return send(res,200,{order:publicOrderView(order)});method(req,"POST");const input=body(req),action=req.query?.action||req.action;if(action==="quote-decision")return send(res,200,{order:await ops.customerQuoteDecision(repository,id,claims.sub,input.decision)});if(action==="change-order-decision")return send(res,200,{order:await ops.customerChangeDecision(repository,id,claims.sub,input.decision)});throw Object.assign(new Error("UNKNOWN_ACTION"),{statusCode:404});});}
function fiscalReviewHandler({repository,secretValue}={}){return wrap(async(req,res)=>{method(req,"POST");const claims=authorize(req,"FISCAL_REVIEW",{secretValue});return send(res,200,{order:await ops.reviewFiscal(repository,req.query?.id||req.id,claims,body(req))});});}
module.exports={body,providerHandler,adminHandler,customerHandler,fiscalReviewHandler};
