"use strict";
const crypto=require("node:crypto");
const {getServiceByCode,CATALOG_VERSION}=require("../catalog");
const {createCatalogPricingSnapshot}=require("../services/pricing-engine");
const {createOrder}=require("../domain/order-engine");
const {createOrderResponsibilityMatrix}=require("../domain/launch-compliance");
const {recordCustomerTermsAcceptance}=require("./contract-authority");
const allowedMaterialModes=new Set(["NONE","CUSTOMER_SUPPLIED","PARTNER_PURCHASE"]);
function assertText(value,name,max=500){if(typeof value!=="string"||!value.trim()||value.length>max)throw Object.assign(new Error(`INVALID_${name.toUpperCase()}`),{statusCode:400});return value.trim();}
function publicOrderView(order){return Object.freeze({orderId:order.orderId,protocol:order.protocol,serviceCode:order.serviceId,serviceName:order.serviceName,category:order.category,pricingMode:order.pricingMode,price:order.pricingMode==="FIXED"?{amountCents:order.pricingSnapshot.customerFinalTotalCents,currency:"BRL"}:null,status:order.status,scheduledAt:order.scheduledAt,createdAt:order.createdAt,catalogVersion:order.catalogVersion});}
async function createCustomerOrder(input,{repository,idempotencyKey}){if(!idempotencyKey)throw Object.assign(new Error("IDEMPOTENCY_KEY_REQUIRED"),{statusCode:400});const service=getServiceByCode(input?.serviceCode);if(!service)throw Object.assign(new Error("UNKNOWN_OFFICIAL_SERVICE"),{statusCode:400});const address=input.address||{};const sanitized={description:assertText(input.description,"description"),address:{street:assertText(address.street,"street",120),number:assertText(address.number,"number",20),complement:typeof address.complement==="string"?address.complement.slice(0,80):"",neighborhood:assertText(address.neighborhood,"neighborhood",80),city:assertText(address.city,"city",80),reference:typeof address.reference==="string"?address.reference.slice(0,120):""},urgency:["Agora","Hoje","Amanhã","Agendar"].includes(input.urgency)?input.urgency:null,materialMode:allowedMaterialModes.has(input.materialMode)?input.materialMode:"NONE",customer:{name:assertText(input.customer?.name,"customer_name",120),whatsapp:assertText(input.customer?.whatsapp,"customer_phone",30),marketingConsent:input.marketingConsent===true},location:null};if(!sanitized.urgency)throw Object.assign(new Error("INVALID_URGENCY"),{statusCode:400});if(input.location?.consent===true&&Number.isFinite(input.location.latitude)&&Number.isFinite(input.location.longitude))sanitized.location={latitude:input.location.latitude,longitude:input.location.longitude,accuracy:Number(input.location.accuracy)||null,capturedAt:input.location.capturedAt||new Date().toISOString(),source:"ONE_TIME_LOCATION",consent:true};const pricingSnapshot=service.pricingMode==="FIXED"?createCatalogPricingSnapshot(service.code):null;const customerId=`CUS-${crypto.randomUUID()}`;const order=createOrder({customerId,serviceId:service.code,category:service.category,description:sanitized.description,latitude:sanitized.location?.latitude,longitude:sanitized.location?.longitude,address:sanitized.address,pricingSnapshot,scheduledAt:input.scheduledAt||null,materialMode:sanitized.materialMode,actor:"CUSTOMER"},`server:${idempotencyKey}`);Object.assign(order,{serviceName:service.name,pricingMode:service.pricingMode,catalogVersion:CATALOG_VERSION,customer:sanitized.customer,location:sanitized.location,urgency:sanitized.urgency,responsibilityMatrix:createOrderResponsibilityMatrix(order.orderId),termsAcceptance:recordCustomerTermsAcceptance({customerId,orderId:order.orderId,accepted:input.termsAcceptance?.accepted})});const saved=await repository.create(order,idempotencyKey);return{order:saved,publicView:publicOrderView(saved)};}
module.exports={createCustomerOrder,publicOrderView};
