"use strict";
const {send,wrap}=require("./http"),{productionRateLimiter,requestIdentity}=require("./rate-limit"),{productionProviderRepository}=require("./provider-repository"),{providerSelfProjection}=require("./provider-review-service"),registration=require("./provider-registration-flow"),{passwordDigest,signSession,productionSessionSecret,authorize}=require("./auth"),{reverseGeocode}=require("./geocoding-provider"),{productionPrivateFileStorage}=require("./private-file-storage");
function body(req){if(req.body&&typeof req.body==="object")return req.body;if(typeof req.body==="string")try{return JSON.parse(req.body)}catch{}throw Object.assign(new Error("INVALID_JSON_BODY"),{statusCode:400});}
function createHandler({repository,rateLimiter,secretValue,geocoder=reverseGeocode,storage}={}){return wrap(async(req,res)=>{const repo=repository||productionProviderRepository(),getProvider=id=>repo.getProvider?repo.getProvider(id):repo.get(id),saveProvider=value=>repo.saveProvider?repo.saveProvider(value):repo.save(value),route=req.query?.route||req.url?.split("?")[0].split("/").pop(),limiter=rateLimiter;if(limiter)await limiter.assert({scope:`provider-${route}`,identity:requestIdentity(req),limit:10});
  if(req.method==="POST"&&route==="register-start"){const result=await registration.start({repository:repo,input:body(req),req,secretValue:secretValue||productionSessionSecret()});return send(res,result.reused?200:201,result);}
  if(req.method==="POST"&&route==="register-document"){const result=await registration.upload({repository:repo,storage:storage||productionPrivateFileStorage(),providerId:req.query?.id||req.id,input:body(req),req,secretValue:secretValue||productionSessionSecret()});return send(res,result.reused?200:201,{evidenceId:result.evidenceId,documentType:result.type,status:result.status,reused:Boolean(result.reused)});}
  if(req.method==="POST"&&route==="register-finalize"){const provider=await registration.finalize({repository:repo,providerId:req.query?.id||req.id,req,secretValue:secretValue||productionSessionSecret()});return send(res,200,{provider:providerSelfProjection(provider),message:"Cadastro enviado para análise humana."});}
  if(req.method==="POST"&&route==="register")throw Object.assign(new Error("REGISTRATION_FLOW_UPDATED"),{statusCode:409,publicMessage:"Atualize a página e tente novamente."});
  if(req.method==="POST"&&route==="login"){const input=body(req),provider=await repo.findByLogin(input.login);if(!provider||passwordDigest(input.password,provider.passwordSalt)!==provider.passwordHash)throw Object.assign(new Error("INVALID_CREDENTIALS"),{statusCode:401});const token=signSession({sub:provider.providerId,role:"PROVIDER"},{secretValue:secretValue||productionSessionSecret(),ttlSeconds:86400});return send(res,200,{token,provider:providerSelfProjection(provider)});}
  if(req.method==="POST"&&route==="geocode"){const input=body(req),latitude=Number(input.latitude),longitude=Number(input.longitude);if(!Number.isFinite(latitude)||latitude< -90||latitude>90||!Number.isFinite(longitude)||longitude< -180||longitude>180)throw Object.assign(new Error("INVALID_COORDINATES"),{statusCode:400});return send(res,200,await geocoder({latitude,longitude}));}
  const claims=authorize(req,"PROVIDER_OPERATE",{secretValue:secretValue||productionSessionSecret()});if(req.method==="GET"&&route==="me"){const provider=await getProvider(claims.sub);if(!provider)throw Object.assign(new Error("NOT_FOUND"),{statusCode:404});return send(res,200,{provider:providerSelfProjection(provider)});}
  if(req.method==="POST"&&route==="documents"){const type=req.query?.id||req.id,input=body(req),provider=await getProvider(claims.sub);if(!provider)throw Object.assign(new Error("NOT_FOUND"),{statusCode:404});const correction=(provider.correctionRequests||[]).find(item=>item.documentType===type&&item.status==="OPEN");if(!correction)throw Object.assign(new Error("DOCUMENT_CORRECTION_NOT_REQUESTED"),{statusCode:409});const purpose=type==="PROFILE_PHOTO"?"PROFILE_PHOTO":"PROVIDER_DOCUMENT",saved=await(storage||productionPrivateFileStorage()).put({ownerId:claims.sub,purpose,originalName:input.originalName,mimeType:input.mimeType,bytes:Buffer.from(input.base64||"","base64")}),previous=provider.documents[type],submittedAt=new Date().toISOString();provider.documents={...provider.documents,[type]:{type,evidenceId:saved.evidenceId,status:"SUBMITTED",submittedAt,history:[...(previous?.history||[]),previous].filter(Boolean)}};provider.correctionRequests=provider.correctionRequests.map(item=>item===correction?{...item,status:"RESUBMITTED",resubmittedAt:submittedAt,newEvidenceId:saved.evidenceId}:item);provider.status="RESUBMITTED";provider.onboardingStatus="RESUBMITTED";provider.updatedAt=submittedAt;await saveProvider(provider);return send(res,201,{document:{type,evidenceId:saved.evidenceId,status:"SUBMITTED",submittedAt},providerStatus:"RESUBMITTED"});}
  throw Object.assign(new Error("NOT_FOUND"),{statusCode:404});});}
module.exports=(req,res)=>createHandler({rateLimiter:productionRateLimiter()})(req,res);module.exports.createHandler=createHandler;
