"use strict";
const crypto=require("node:crypto"),{send,wrap}=require("./http"),{productionRateLimiter,requestIdentity}=require("./rate-limit"),{productionProviderRepository}=require("./provider-repository"),{createProvider,privateProjection}=require("./provider-onboarding"),{passwordDigest,signSession,productionSessionSecret,authorize}=require("./auth"),{reverseGeocode}=require("./geocoding-provider"),{productionPrivateFileStorage}=require("./private-file-storage");
function body(req){if(req.body&&typeof req.body==="object")return req.body;if(typeof req.body==="string")try{return JSON.parse(req.body)}catch{}throw Object.assign(new Error("INVALID_JSON_BODY"),{statusCode:400});}
function createHandler({repository,rateLimiter,secretValue,geocoder=reverseGeocode,storage}={}){return wrap(async(req,res)=>{const repo=repository||productionProviderRepository(),route=req.query?.route||req.url?.split("?")[0].split("/").pop(),limiter=rateLimiter;if(limiter)await limiter.assert({scope:`provider-${route}`,identity:requestIdentity(req),limit:10});
  if(req.method==="POST"&&route==="register"){const input=body(req),providerId=`PRV-${crypto.randomUUID()}`;if(input.documentUploads){const target=storage||productionPrivateFileStorage(),documents={};for(const [type,file] of Object.entries(input.documentUploads)){const saved=await target.put({ownerId:providerId,purpose:type==="BACKGROUND_CHECK"?"BACKGROUND_CHECK":type==="PROFILE_PHOTO"?"PROFILE_PHOTO":"PROVIDER_DOCUMENT",originalName:file.originalName,mimeType:file.mimeType,bytes:Buffer.from(file.base64||"","base64")});documents[type]=saved.evidenceId;}input.documents=documents;delete input.documentUploads;}const provider=createProvider(input,{providerId});await repo.create(provider);return send(res,201,{provider:privateProjection(provider),message:"Cadastro enviado para análise humana."});}
  if(req.method==="POST"&&route==="login"){const input=body(req),provider=await repo.findByLogin(input.login);if(!provider||passwordDigest(input.password,provider.passwordSalt)!==provider.passwordHash)throw Object.assign(new Error("INVALID_CREDENTIALS"),{statusCode:401});const token=signSession({sub:provider.providerId,role:"PROVIDER"},{secretValue:secretValue||productionSessionSecret(),ttlSeconds:86400});return send(res,200,{token,provider:privateProjection(provider)});}
  if(req.method==="POST"&&route==="geocode"){const input=body(req),latitude=Number(input.latitude),longitude=Number(input.longitude);if(!Number.isFinite(latitude)||latitude< -90||latitude>90||!Number.isFinite(longitude)||longitude< -180||longitude>180)throw Object.assign(new Error("INVALID_COORDINATES"),{statusCode:400});return send(res,200,await geocoder({latitude,longitude}));}
  if(route==="admin-list"&&req.method==="GET"){authorize(req,"ADMIN_READ",{secretValue:secretValue||productionSessionSecret()});const providers=await repo.list();return send(res,200,{providers:providers.map(privateProjection)});}
  if(route==="admin-review"&&req.method==="POST"){const admin=authorize(req,"ADMIN_WRITE",{secretValue:secretValue||productionSessionSecret()}),input=body(req),provider=await repo.get(input.providerId);if(!provider)throw Object.assign(new Error("NOT_FOUND"),{statusCode:404});if(input.documentType){const document=provider.documents?.[input.documentType];if(!document)throw Object.assign(new Error("DOCUMENT_NOT_FOUND"),{statusCode:404});if(!["UNDER_REVIEW","VALIDATED","REJECTED","EXPIRED"].includes(input.status))throw Object.assign(new Error("INVALID_DOCUMENT_STATUS"),{statusCode:400});if(input.status==="REJECTED"&&!String(input.reason||"").trim())throw Object.assign(new Error("REJECTION_REASON_REQUIRED"),{statusCode:400});Object.assign(document,{status:input.status,reason:String(input.reason||"").trim()||null,reviewedBy:admin.sub,reviewedAt:new Date().toISOString()});}if(input.providerStatus){if(!["UNDER_REVIEW","DOCUMENTS_REQUIRED","APPROVED","SUSPENDED"].includes(input.providerStatus))throw Object.assign(new Error("INVALID_PROVIDER_STATUS"),{statusCode:400});provider.status=input.providerStatus;provider.active=input.providerStatus!=="SUSPENDED";}provider.updatedAt=new Date().toISOString();await repo.save(provider);return send(res,200,{provider:privateProjection(provider)});}
  const claims=authorize(req,"PROVIDER_OPERATE",{secretValue:secretValue||productionSessionSecret()});if(req.method==="GET"&&route==="me"){const provider=await repo.get(claims.sub);if(!provider)throw Object.assign(new Error("NOT_FOUND"),{statusCode:404});return send(res,200,{provider:privateProjection(provider)});}throw Object.assign(new Error("NOT_FOUND"),{statusCode:404});});}
module.exports=(req,res)=>createHandler({rateLimiter:productionRateLimiter()})(req,res);module.exports.createHandler=createHandler;
