"use strict";
const WHATSAPP_NUMBER="5531990102500";
const statuses=["Solicitação recebida","Buscando profissional","Profissional designado","Profissional a caminho","Chegou ao local","Serviço em andamento","Serviço finalizado"];
let selectedServiceCode="",selectedUrgency="",currentStep=1,currentOrder=null;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const escapeHtml=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money=c=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(c/100);
const whatsappUrl=m=>`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(m)}`;
const showToast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)};
function trackWhatsappConversion(){if(typeof window.gtag==="function")window.gtag("event","conversion",{send_to:"AW-17424041657/Rb7QCI780u4cELmNt_RA"});}
function showView(name){const view=$(`#${name}-view`);if(!view)return false;$$('.view').forEach(v=>v.classList.remove('active'));view.classList.add('active');view.removeAttribute?.('aria-hidden');$$('.view').filter(v=>v!==view).forEach(v=>v.setAttribute?.('aria-hidden','true'));window.scrollTo({top:0,behavior:'smooth'});if(name==='tracking')renderTracking();return true;}
function serviceLabel(service){return service.pricingMode==='QUOTE'?`${service.name} — Sob orçamento`:`${service.name} — ${money(service.customerPriceCents)}`;}
function renderStatic(){
 const catalog=globalThis.ReformaProfissionalCatalog.catalog;
 const categories=[...new Set(catalog.map(s=>s.category))];
 $('#service-types').innerHTML=categories.map(c=>`<button type="button" class="choice" data-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('')+'<label class="wide">Serviço<select id="official-service" required><option value="">Escolha primeiro uma categoria</option></select></label>';
 $('.trust-strip').innerHTML=["Profissionais verificados","Atendimento rápido","Segurança para o cliente","Orçamento transparente","Acompanhamento","Suporte via WhatsApp"].map(x=>`<div class="trust-item"><i>✓</i><span>${x}</span></div>`).join('');
 const popular=catalog.slice(0,14);$('#popular-services').innerHTML=popular.map(s=>`<button type="button" class="service-card" data-code="${s.code}" aria-label="Selecionar ${escapeHtml(s.name)}"><b>${escapeHtml(s.name)}</b><span aria-hidden="true">→</span></button>`).join('');
 $('#common-problems').innerHTML=catalog.slice(14,29).map(s=>`<button type="button" class="chip" data-code="${s.code}">${escapeHtml(s.name)}</button>`).join('');
 $('#construction-services').innerHTML=catalog.filter(s=>s.category==='REFORMA E CONSTRUÇÃO').slice(0,21).map(s=>`<button type="button" class="chip" data-code="${s.code}">${escapeHtml(s.name)}</button>`).join('');
 $('#assistant-options').innerHTML='<button type="button" data-start>Ver catálogo oficial</button>';$('#urgency-options').innerHTML=['Agora','Hoje','Agendar'].map(x=>`<button type="button" class="choice" data-urgency="${x}">${x}</button>`).join('');$('#safety-list').innerHTML=["Profissional identificado","Atendimento registrado","Suporte via WhatsApp","Preço oficial ou orçamento","Avaliação após o serviço"].map(x=>`<div class="safety-item"><span>✓</span>${x}</div>`).join('');
 $$('.whatsapp-general').forEach(a=>a.href=whatsappUrl('Olá, vim pelo app Reforma Profissional e quero solicitar um serviço.'));$('#year').textContent=new Date().getFullYear();
}
function selectService(code){const s=globalThis.ReformaProfissionalCatalog.getServiceByCode(code);if(!s)return;selectedServiceCode=s.code;$$('[data-category]').forEach(b=>b.classList.toggle('selected',b.dataset.category===s.category));const sel=$('#official-service');sel.innerHTML=globalThis.ReformaProfissionalCatalog.catalog.filter(x=>x.category===s.category).map(x=>`<option value="${x.code}">${escapeHtml(serviceLabel(x))}</option>`).join('');sel.value=s.code;const label=serviceLabel(s);$('#selected-detail').hidden=false;$('#selected-detail').textContent=label;$('#selected-service-summary').textContent=`Serviço selecionado: ${label}`;}
function resetRequest(){selectedServiceCode='';selectedUrgency='';currentStep=1;$('#request-form').reset();$('#selected-detail').hidden=true;$('#selected-detail').textContent='';$('#selected-service-summary').textContent='';$('#schedule-field').hidden=true;$$('[data-category],[data-urgency]').forEach(button=>button.classList.remove('selected'));}
function startRequest(code=''){resetRequest();showView('request');showStep(1);if(code)selectService(code);}
function activateServiceCard(code){startRequest(code);if(!selectedServiceCode)return false;showStep(2);return true;}
function showStep(step){currentStep=Math.max(1,Math.min(4,step));$$('.form-step').forEach(x=>x.classList.toggle('active',+x.dataset.step===currentStep));$$('.step',$('#request-view')).forEach((x,i)=>{x.classList.toggle('active',i+1===currentStep);x.classList.toggle('done',i+1<currentStep)});$('#prev-step').hidden=currentStep===1;$('#next-step').hidden=currentStep===4;$('#submit-request').hidden=currentStep!==4;$('#form-error').hidden=true;}
function fail(msg,field){const e=$('#form-error');e.textContent=msg;e.hidden=false;showToast(msg);field?.focus();return false;}
function validate(step){const f=$('#request-form');if(step===1&&!selectedServiceCode)return fail('Escolha um serviço oficial para continuar.',$('#official-service'));if(step===2){if(!f.description.value.trim())return fail('Descreva o problema.',f.description);if(!selectedUrgency)return fail('Escolha a urgência.',$('[data-urgency]'));if(selectedUrgency==='Agendar'&&!f.schedule.value)return fail('Informe data e horário.',f.schedule)}if(step===3)for(const n of ['address','number','neighborhood','city'])if(!f[n].value.trim())return fail(`Preencha ${n}.`,f[n]);if(step===4){if(!f.name.value.trim()||!f.whatsapp.value.trim()||!f.terms.checked)return fail('Preencha os dados e aceite os termos.',f.name)}return true;}
async function readJsonResponse(response){const contentType=response.headers?.get?.('content-type')||'';if(!contentType.toLowerCase().includes('application/json'))throw new Error('O servidor respondeu em formato inesperado. Seus dados foram preservados; tente novamente.');try{return await response.json();}catch{throw new Error('Não foi possível interpretar a resposta do servidor. Seus dados foram preservados; tente novamente.');}}
async function submit(event){event.preventDefault();if(!validate(4))return;const f=event.currentTarget,b=$('#submit-request');b.disabled=true;const payload={serviceCode:selectedServiceCode,description:f.description.value.trim(),address:{street:f.address.value.trim(),number:f.number.value.trim(),complement:f.complement.value.trim(),neighborhood:f.neighborhood.value.trim(),city:f.city.value.trim(),reference:f.reference.value.trim()},location:f.latitude.value?{latitude:Number(f.latitude.value),longitude:Number(f.longitude.value),accuracy:Number(f.locationAccuracy.value),capturedAt:f.locationTimestamp.value,source:'BROWSER_GEOLOCATION',consent:true}:null,urgency:selectedUrgency,scheduledAt:f.schedule.value||null,materialMode:'NONE',customer:{name:f.name.value.trim(),whatsapp:f.whatsapp.value.trim()},marketingConsent:f.marketingConsent?.checked===true};try{const response=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(payload)});const body=await readJsonResponse(response);if(!response.ok)throw new Error(body.error||'Não foi possível criar a solicitação.');currentOrder=body;sessionStorage.setItem('reforma-profissional-order-reference',JSON.stringify(body));$('#success-protocol').textContent=body.protocol;$('#success-whatsapp').href=whatsappUrl(`Olá, quero acompanhar minha solicitação. Protocolo: ${body.protocol}`);showView('success');}catch(error){fail(error.message);}finally{b.disabled=false;}}
function renderTracking(){const o=currentOrder||(()=>{try{return JSON.parse(sessionStorage.getItem('reforma-profissional-order-reference'))}catch{return null}})();$('#empty-tracking').hidden=!!o;$('#tracking-content').hidden=!o;if(!o)return;$('#tracking-protocol').textContent=`Protocolo ${o.protocol}`;$('#map-address').textContent='Endereço protegido';$('#map-status').textContent=o.status;$('#status-timeline').innerHTML=statuses.map((s,i)=>`<li class="${i===0?'current':''}">${s}</li>`).join('');$('#payment-panel').hidden=true;$('#provider-whatsapp').href=whatsappUrl(`Olá, preciso de suporte para o protocolo ${o.protocol}`);$('#notifications-list').innerHTML='<div class="notification-item"><i>✓</i><div><b>Solicitação recebida</b></div></div>';}
function bind(){document.addEventListener('click',e=>{const target=e.target instanceof Element?e.target:e.target?.parentElement;if(!target)return;const service=target.closest('[data-code]');if(service){activateServiceCard(service.dataset.code);return}const start=target.closest('[data-start]');if(start){startRequest();return}const v=target.closest('[data-view]');if(v){showView(v.dataset.view);return}const cat=target.closest('[data-category]');if(cat){const items=globalThis.ReformaProfissionalCatalog.catalog.filter(x=>x.category===cat.dataset.category);$$('[data-category]').forEach(b=>b.classList.toggle('selected',b===cat));$('#official-service').innerHTML='<option value="">Selecione o serviço</option>'+items.map(x=>`<option value="${x.code}">${escapeHtml(serviceLabel(x))}</option>`).join('');selectedServiceCode='';return}const urg=target.closest('[data-urgency]');if(urg){selectedUrgency=urg.dataset.urgency;$$('[data-urgency]').forEach(b=>b.classList.toggle('selected',b===urg));$('#schedule-field').hidden=selectedUrgency!=='Agendar';return}if(target.closest('.whatsapp-general'))trackWhatsappConversion();});
 $('#official-service').addEventListener('change',e=>selectService(e.target.value));$('#next-step').addEventListener('click',()=>{if(validate(currentStep))showStep(currentStep+1)});$('#prev-step').addEventListener('click',()=>showStep(currentStep-1));$('#request-form').addEventListener('submit',submit);$('#get-location').addEventListener('click',()=>{if(!navigator.geolocation){$('#location-status').textContent='GPS indisponível. Informe o endereço manualmente.';return}navigator.geolocation.getCurrentPosition(p=>{const f=$('#request-form');f.latitude.value=p.coords.latitude;f.longitude.value=p.coords.longitude;f.locationAccuracy.value=p.coords.accuracy;f.locationTimestamp.value=new Date(p.timestamp).toISOString();$('#location-status').textContent='Localização pontual autorizada.';},()=>{$('#location-status').textContent='Localização não autorizada. Informe o endereço manualmente.';},{enableHighAccuracy:true,timeout:10000,maximumAge:300000})});$('#share-tracking').addEventListener('click',()=>{});}
function init(){renderStatic();bind();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}
const publicApi={init,startRequest,activateServiceCard,selectService,showStep,showView,getState:()=>({selectedServiceCode,selectedUrgency,currentStep})};
if(typeof module==='object'&&module.exports)module.exports=publicApi;else init();
